/* excludedLunarContainers.js
 *
 * Stores the items to be excluded from being assigned a Lunar-Button-Container
 * @params: None
 * @returns: None
 */

export const excludedLabels = [
  "Lunar Eclipse",
  "Scout Mastery",
  "Agent Mastery",
  "Bowman Mastery",
  "Blaster Mastery",
  "Trigger Mastery",
  "Detective Mastery",
  "Vince Mastery",
  "Marksman Mastery",
  "Gold Plated",
  "Year Cape",
  "Nuke Tamer",
  "USS Krunk",
  "Shuriken",
  "Bizon",
  "High Roller",
  "Master Trader",
  "Citizen's Arrest",
  "Killa",
  "Pay Piggie",
  "Krunk Twerk",
  "Exhausted",
  "Dashing",
  "SMAW",
  "AUG",
  "AEK-999",
  "1 year cape",
  "1-gor jacket",
  "1-gor outlaw",
  "1911",
  "2 year cape",
  "2023 deployed",
  "2023 glasses",
  "3 year cape",
  "4 year cape",
  "a",
  "abyss",
  "actual nr.1",
  "aftermath",
  "ahoy's spirit",
  "ai",
  "aim bot",
  "aimbot",
  "air drop",
  "aj47",
  "alien microbe",
  "all-man",
  "angry",
  "angry hero",
  "anti-hero",
  "antidote",
  "ap rally",
  "apex predator",
  "apprentice's might",
  "ar-comp",
  "arctic drake",
  "arcturus",
  "argentina trikot",
  "aromatic blade",
  "array",
  "atomize",
  "attack drone",
  "augmented",
  "aurum body",
  "aurum head",
  "aurum shoes",
  "aurum waist",
  "aussieantics",
  "australia trikot",
  "avenger",
  "avenger-x",
  "axx",
  "b",
  "back to skool",
  "bad day",
  "baka",
  "bakuretsu",
  "baluba",
  "bamboo",
  "barebones",
  "basedef-2",
  "bats",
  "be like joe",
  "beaten",
  "beetlejuice",
  "behemoth",
  "belgium trikot",
  "beltium",
  "beluga",
  "big meat",
  "big spook",
  "biohazard",
  "birb",
  "black balaclava",
  "blade 23",
  "blizzardious",
  "bloat-mobile",
  "bloated",
  "blockstream",
  "bloodthirster",
  "blue digital",
  "blue tiger",
  "bluezea",
  "boarded",
  "bob.",
  "bolted",
  "boo!",
  "boom!",
  "bounty hunter",
  "brain massage",
  "brainz",
  "brasil trikot",
  "breach",
  "broken",
  "bronze blade",
  "bronze cyberedge",
  "bruisegg",
  "bucket",
  "buckled up",
  "building",
  "bullet loop",
  "bun",
  "bunny gamer",
  "bunny gun",
  "bunny shoes",
  "bunny suspenders",
  "bunny tail",
  "burg diorama",
  "burg invasion",
  "bushido's honor",
  "byakko",
  "c",
  "cafe lancer",
  "calavera",
  "cameroon trikot",
  "canada trikot",
  "canned trip",
  "capt krunk",
  "captain cold",
  "captain star-z",
  "captain's pride",
  "caretaker",
  "carnage friends",
  "carroperator",
  "carroperator belt",
  "carroperator boots",
  "carroperator vest",
  "carrot rev",
  "carrotana",
  "casle",
  "cat headphones",
  "catgirl",
  "celebration bottle",
  "celebrations",
  "celeste",
  "celestialdragon",
  "chaffee",
  "chained",
  "chainsaw",
  "chalk 'em up",
  "champions",
  "chaos + control",
  "charity",
  "charmer",
  "check",
  "cheeky",
  "cherry blossom",
  "chicky",
  "chorose",
  "chrgdup",
  "christmas cutter",
  "chunchunmaru",
  "chunky omen",
  "citadel diorama",
  "citadel tophat",
  "clockwork",
  "clockwork diorama",
  "clover",
  "clueless",
  "cockatrice",
  "coffin cannon",
  "color your world",
  "combat boots",
  "comic striker",
  "comic tracker",
  "confetti",
  "consp11re",
  "controlly",
  "costa rica trikot",
  "cotton candy",
  "crayator bandana",
  "creep",
  "croatia trikot",
  "crossed out",
  "crowsnest",
  "crusader",
  "cupids blaster",
  "cyber chad",
  "cyber mov",
  "cyber punk",
  "cyber visor",
  "cyber-kill ghost",
  "cyberblast",
  "cyberclaw",
  "cyberdragon",
  "cyberdrake",
  "cyberlex",
  "cybertigger",
  "cytek-krnk",
  "dainty shoes",
  "danger ahead",
  "dark standard issue",
  "de-humanizer",
  "defender-x",
  "delicious love",
  "denmark trikot",
  "desert hare",
  "destiny",
  "devil horns",
  "devious",
  "deviously",
  "dia de muertos",
  "diamond blade",
  "diamond cyberedge",
  "digiarmor",
  "dipped blackout",
  "distinguished bunny",
  "double barrelled",
  "double tnt",
  "dr.mainframe",
  "draco",
  "dracrunic",
  "dragmota",
  "dragon dimension",
  "dragon's eye",
  "dragon's mark",
  "dragon's realm",
  "drake's wrath",
  "drift kill",
  "drizzy",
  "drowzy",
  "duck hunt",
  "echoo",
  "ectoplasm",
  "ectopollo",
  "ecuador trikot",
  "edgerunner",
  "egg basket",
  "egg hunt",
  "egg launcher",
  "egg shelled",
  "egg top",
  "elimination",
  "ember lord",
  "embers",
  "emoji beanie",
  "emperor's blade",
  "england trikot",
  "enter the hxllxw",
  "escorpio",
  "eternal flame",
  "eternal rest",
  "evacuated",
  "evacuation diorama",
  "evil",
  "evo-s2k2",
  "exile",
  "eyes on you",
  "faceless",
  "familia",
  "fan language",
  "fermenter",
  "festive flyer",
  "festive hat",
  "ffastforward",
  "fierce spirit",
  "files",
  "final stand",
  "fire place",
  "firework tamer",
  "first watch",
  "fish-faced",
  "flamelurker",
  "flying dutchman",
  "football",
  "forbidden tome",
  "forever glasses",
  "forever hunting",
  "forever kilt",
  "forever shirt",
  "forever shoes",
  "france trikot",
  "frankie",
  "free skins",
  "freight diorama",
  "freighted",
  "freshly picked",
  "froge",
  "frosty",
  "fubai",
  "fused",
  "future door",
  "future fighter",
  "games for love",
  "gatekeeper",
  "gatekeeper belt",
  "gatekeeper tanktop",
  "gatekeeper walkers",
  "germany trikot",
  "ghana trikot",
  "ghast",
  "ghostie",
  "ghostly",
  "ghostly cowboy",
  "gifted",
  "gifted blade",
  "ginger python",
  "gingerbread",
  "gingerbread suit",
  "glace",
  "gloriou pompadour",
  "gluton",
  "gold blade",
  "gold cyberedge",
  "gold cz",
  "golden turkey",
  "good ending",
  "good'ol'belt",
  "good'ol'boots",
  "good'ol'mask",
  "good'ol'pistol",
  "good'ol'smg",
  "good'ol'vest",
  "goofball",
  "grandmaster's smite",
  "greedy",
  "green digital",
  "green tiger",
  "grill time",
  "grinner",
  "gruelling grind",
  "guardian of atlantis",
  "gunmetal circuit",
  "gunslinger",
  "hail the night",
  "halitus ignis",
  "halloween",
  "halloween night",
  "hana's retribution",
  "happy 2023",
  "happy alien",
  "hateful flesh",
  "haunter",
  "helios m2",
  "hellrider",
  "helm of the husky",
  "hero's advice",
  "hero's might",
  "hex matrix",
  "hip",
  "hiz-001",
  "holiday cheer",
  "holland trikot",
  "hoppy easter",
  "hue fever",
  "hush",
  "hzr-d",
  "i love krum",
  "i see you",
  "imouto!",
  "impish",
  "industrial",
  "industry diorama",
  "infected",
  "infected body",
  "infected string",
  "inflated",
  "inhumane armour",
  "inhumane belt",
  "inhumane boots",
  "inhumane helmet",
  "inhumane!",
  "inix",
  "inquisitor's cyberblade",
  "into the void",
  "invader",
  "iran trikot",
  "jade tiger",
  "japan trikot",
  "jimbo",
  "joe's dinner knife",
  "joe's face",
  "joe's hat",
  "joe's overall",
  "joe's utility belt",
  "jolly saint",
  "jormungandr's venom",
  "juice box",
  "just deagling",
  "just hanging",
  "just slicing",
  "k.r.p.d assault helmet",
  "k.r.p.d stalker",
  "kaartana",
  "kali",
  "kama",
  "kamouflage",
  "kanagawa king",
  "kanav",
  "kanji diorama",
  "kanjipd",
  "kanjo",
  "kaptain k",
  "keniro pd",
  "killer clown",
  "kohaku",
  "koltron x",
  "korea republic trikot",
  "kork launcher",
  "krockets",
  "krocs",
  "krpd cruiser",
  "krpd gunship",
  "krpd hq",
  "krpd negotiator",
  "krpd recruit blade",
  "krpd utility belt",
  "krpd vest",
  "krum cape",
  "krum dispenser",
  "krum juicer",
  "krunk-o-ween",
  "krunkenstein",
  "krunkerprise",
  "krunkinator",
  "krunkmas cloak",
  "krunksgiving",
  "krunkstar",
  "krypto blade",
  "krypton body",
  "krypton head",
  "krypton shoes",
  "krypton waist",
  "krystallizer",
  "ku-nai_dn",
  "lagoon diorama",
  "lbm",
  "lbm belt",
  "lbm cape",
  "lbm mask",
  "lead dispenser",
  "legend's might",
  "limech",
  "lineup",
  "little truck",
  "littletown diorama",
  "lordship",
  "loserfruit bandana",
  "lost humanity",
  "lost in time",
  "lost souls",
  "lostworld diorama",
  "love beanie",
  "love belt",
  "love shoes",
  "love top",
  "lover boy",
  "lover girl",
  "lovestruck",
  "lucky belt",
  "lucky clover",
  "lucky famas",
  "lucky hat",
  "lucky shoes",
  "lucky skull",
  "lucky top",
  "lumber diorama",
  "lumberjack",
  "lunar eclipse",
  "lunar temple",
  "macuahuitl",
  "magic carpet",
  "magic wand",
  "maid's apron",
  "maid's bonnet",
  "maid's skirt",
  "makeshift",
  "mane attraction",
  "marauders cleaver",
  "mark of the tigress",
  "marrowborne",
  "master blade",
  "master cyberedge",
  "matryoshka",
  "maximum boost",
  "mayumi-7",
  "meat market",
  "mecha bunny",
  "merry kill-mas",
  "messy",
  "mexico trikot",
  "mi0 armour",
  "mi0 boots",
  "mi0 helmet",
  "minitown",
  "mirror's cutlass",
  "mocksidz",
  "mommys money",
  "monoeye",
  "mood",
  "mood 2.0",
  "moon lander",
  "moondrake",
  "moonflyer",
  "morb",
  "morocco trikot",
  "mother's den",
  "mr krabs",
  "nav",
  "necromancer",
  "neko-90",
  "neon tigress",
  "neptune",
  "night predator",
  "night stalker",
  "nikorienka",
  "no witnesses",
  "nocturnal",
  "noël",
  "nuclear",
  "nuke cracker",
  "nya",
  "oasis diorama",
  "oasis guardian",
  "officer buddy",
  "og",
  "ok dude",
  "oldie",
  "omegasoul",
  "on site",
  "optic",
  "optimus-0",
  "orange digital",
  "orange tiger",
  "outlaw",
  "outlaw boots",
  "outlaw brainiac",
  "outlaw gadgets",
  "p1ckme",
  "palm hair",
  "panda headphones",
  "panda paws",
  "parade poncho",
  "party time!",
  "patricia",
  "pearl",
  "penciler",
  "pepe slippers",
  "peppermint pal",
  "peppermint piercer",
  "physs",
  "pick me",
  "pie",
  "pink digital",
  "pirzo",
  "pistoleer",
  "pixel tiger",
  "plasma cutter",
  "playercard ticket",
  "poland trikot",
  "pompadourian vest",
  "poof!",
  "poom",
  "popper!",
  "porcelain tigress",
  "portugal trikot",
  "pow!",
  "present assault",
  "present basher",
  "presented",
  "prism",
  "prosperity dragon",
  "protector of the night",
  "protun",
  "pullin' up",
  "pumpie",
  "pumpking",
  "puppet master",
  "purple digital",
  "qatar trikot",
  "quacker",
  "quacky bandana",
  "quasar",
  "queen",
  "quiver",
  "raid unob",
  "raider general",
  "raider goon",
  "raiders crest",
  "raiders mbt",
  "raidforbidden tome",
  "raindeer brace",
  "raindeer hoof",
  "raindeer tail",
  "rawrinator",
  "ready to celebrate",
  "recko",
  "red call",
  "red card",
  "red digital",
  "red dot",
  "red killers",
  "red reaper",
  "reindeer antlers",
  "retro-slicer",
  "rev 2078",
  "rezu",
  "riot's bloom",
  "riotalexis",
  "robots in here",
  "rotten arm",
  "royal angel",
  "royal cross",
  "royal heart",
  "royal leader",
  "royal tiger",
  "royal turkey",
  "royals mbt",
  "ruling the realms",
  "rune lord",
  "sacred touch",
  "sandstorm diorama",
  "sandstorm supply",
  "santa's boots",
  "santa's sack",
  "saudi arabia trikot",
  "saurischian",
  "sawblade",
  "screentone",
  "scuffed bandana",
  "senegal trikot",
  "serbia trikot",
  "seriously?",
  "serpent of summer",
  "shark fin",
  "sharkbyte",
  "sharpened crab",
  "shine bright",
  "shiplap",
  "shooting star",
  "sigil of hope",
  "silver blade",
  "silver cyberedge",
  "site diorama",
  "skeletal remains",
  "skelly",
  "skribble face",
  "skullz n bulletz",
  "sky spinner",
  "sky temple diorama",
  "slammer",
  "slimetime",
  "sly carrot",
  "snorkle",
  "snowman body",
  "snowman gang",
  "snowman head",
  "snowman maneater",
  "snowman waist",
  "sorable iv",
  "soul fiend",
  "space captain",
  "space patrol",
  "spacer",
  "spain trikot",
  "spectator",
  "spectral tiger",
  "spook!",
  "spooky",
  "spr-blade",
  "st3-punk",
  "st4lk3r",
  "stabby water",
  "star capper",
  "star power",
  "star shoes",
  "star wand",
  "stardust cape",
  "stardust glider",
  "stardust mask",
  "stardust smirk",
  "starduster",
  "starlight",
  "starlight jet",
  "starlight sight",
  "starlight voyage",
  "starpoint",
  "starry friends",
  "starry visitors",
  "statues",
  "sticker show",
  "stocking stuffer",
  "stompers",
  "strawberry milk",
  "streak",
  "styler",
  "sub gondola",
  "substar",
  "subzero diorama",
  "suetic at home",
  "sugoi",
  "sun beam",
  "sunset predator",
  "super hero",
  "super krunked",
  "super werewolf",
  "superak47",
  "superhero's smite",
  "sussy carrot body",
  "swag bag",
  "swag bag xl",
  "sweet shot",
  "sweet stab",
  "switzerland trikot",
  "swixie",
  "swonky",
  "synopsis",
  "t1ga",
  "t3:33th am",
  "takao 11",
  "take a bite",
  "tan standard issue",
  "target locked",
  "teal tiger",
  "teknika-blade",
  "telescope",
  "temple-top",
  "tgr-011",
  "thanksgiving feast",
  "that's a knife",
  "the chosen one",
  "the dragon's legend",
  "the justice",
  "the maw",
  "the mighty gobbler",
  "the new king",
  "the nutcracker",
  "thiccchemist",
  "third eye",
  "tibetan tiger",
  "tidal swarm",
  "tied up gnomer",
  "tigadelic",
  "tiger",
  "tiger clawed",
  "tiger knife",
  "tiger warfare",
  "tiger's fury",
  "tiger's glare",
  "tiger's might",
  "tigers growl",
  "tigertech",
  "tigracer",
  "tigress dynasty",
  "tigris",
  "tiki",
  "tinybot",
  "to battle!",
  "toby backpack",
  "tombskull",
  "totally normal",
  "tricker",
  "tropical",
  "tropicano diorama",
  "true strength",
  "tryptophobia",
  "tsundeagle",
  "tulip",
  "tunisia trikot",
  "turd",
  "turkey escape",
  "turkey time",
  "tyg-r-24k",
  "umbral harvest",
  "unbelievable",
  "uncanny",
  "undead",
  "undead body",
  "under-cover",
  "undergrowth diorama",
  "unguibus",
  "union",
  "unyielding hero",
  "uruguay trikot",
  "usa trikot",
  "usp 2022",
  "v-drive",
  "valkyrie",
  "vase",
  "venator tigris",
  "vendy",
  "vengeful hero",
  "veteran",
  "vibin",
  "vkingrev",
  "vulkan's chest",
  "vulkan's helmet",
  "vulkan's legs",
  "vulkan's v2000",
  "vulkan's veagle",
  "wales trikot",
  "walker stalker",
  "wanted joe",
  "warlock",
  "watch",
  "wattle",
  "what's in the box?",
  "wheelie bin",
  "whippard",
  "whippington",
  "white tiger",
  "william tell",
  "winter predator",
  "wirestation :d",
  "witch's brew",
  "workers vest",
  "world cup stadium",
  "wormhole",
  "worthy",
  "wraith's wyrm",
  "wrapped up ak",
  "wrapped up deagle",
  "wrapped up famas",
  "wrapped up smg",
  "wrencher",
  "wyvern",
  "wywh",
  "x-23",
  "xenon body",
  "xenon head",
  "xenon shoes",
  "xenon waist",
  "year of the tiger",
  "yearly hunt",
  "z3agle",
  "z3d",
  "zap!",
  "zed bandana",
  "zen",
  "zero ground",
  "zhora ii",
  "znip3r",
  "zombie",
  "zombified",
  "zootiez",
  "zrym",
];
