/* labels.js
 *
 * Stores the Item Label arrays for each rarity
 * @params: None
 * @returns: None
 */

export const nft_labels = [
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
  "Gold Plated",
];

export const unob_labels = [
  "DOS",
  "Vertigo",
  "Esper",
  "Moonfeather",
  "DOS Armour",
  "Exotic",
  "Deep Space",
  "RGB",
  "DOS Belt",
  "DOS Walkers",
  "Ghostie",
  "Attack Drone",
  "Flying Dutchman",
  "Assault Drone",
  "Bruisegg",
  "Forbidden Tome",
  "Frostbite",
  "ZENITH",
  "Mysterious Orb",
  "Eternal Frost",
  "Coroller",
  "Jagdfaust IV",
  "Anti-Matter",
  "Scouts Honor",
  "Keeper Of The Deep",
  "Disintegrator",
  "Devourer Of Souls",
  "ESPER",
];

export const contra_labels = [
  "Bits",
  "Baluba",
  "Matryoshka",
  "Ravatron",
  "Disco Mouse",
  "Robob MKI",
  "Robob MKII",
  "NanoSwarm",
  "High Roller",
  "Master Trader",
  "Matrix",
  "Krunkie Planes",
  "Crown Spinner",
  "Hellrider",
  "Deafeningly Loud",
  "K.R.P.D Assault Helmet",
  "1-GOR Outlaw",
  "Ares Helmet",
  "Even Louder?",
  "The Welder Hat",
  "Inhumane Helmet",
  "GATEKEEPER",
  "Outline",
  "Annoying",
  "Blinker",
  "Bloated",
  "Brainrot",
  "Tiny hat abduction",
  "U.F.0",
  "Prototype-51",
  "Snowy Saucer",
  "Planetarium",
  "Heatmap",
  "Soul Shard",
  "Ice Shard",
  "Krunkanium",
  "Frost Essence",
  "Soul Essence",
  "Uranium",
  "KRPD Cruiser",
  "TV TRON",
  "Lucky cat",
  "Gifted",
  "Royal Cross",
  "Season 6 Ultra Ticket",
  "Season 7 Ultra Ticket",
  "Present Tamer",
  "Sea Tamer",
  "Drift Tamer",
  "Matrix Monitors",
  "Helping Hands",
  "Soul Fiend",
  "Xeno Wings",
  "Nuclear",
  "Skull Tamer",
  "Toilet Tamer",
  "Stardust cape",
  "Vulkan's Chest",
  "KRPD Vest",
  "1-GOR Jacket",
  "4 Year Cape",
  "Amplifier",
  "The Welder",
  "Shattered Spectre",
  "Ares Breath",
  "Honey Wings",
  "Volume Waves",
  "Snowman Body",
  "Firework Tamer",
  "Inhumane Armour",
  "Outlined",
  "Inflated",
  "Egg Tamer",
  "Black Widow",
  "Arachnidis",
  "1 Year Cape",
  "2 Year Cape",
  "Ember Lord",
  "Neon Dance",
  "Infinity Cloak",
  "Captain Galaxy",
  "3 Year Cape",
  "Shattered Asura",
  "Soul Harvest",
  "Nuke Tamer",
  "Observer",
  "Kali",
  "Union",
  "Rune Lord",
  "Plasmacrow",
  "Imagination",
  "Moonlit",
  "Bipolar",
  "Vantablack",
  "Spectralon",
  "K.P.D Uniform",
  "Ghostly",
  "Santa Suit",
  "Gingerbread Suit",
  "Greyscale",
  "Deviously",
  "Burgundy",
  "Floatie",
  "AP Rally",
  "Fighter",
  "KrunkBoard",
  "Cloud Rider",
  "Trolley",
  "USS Krunk",
  "USS TTV",
  "Tornado",
  "Genie",
  "Ares Belt",
  "The Welder Belt",
  "Loud and Proud",
  "Snowman Waist",
  "Bloat-mobile",
  "Unicycle",
  "Magic Carpet",
  "Chaffee",
  "Future Fighter",
  "Star Struck",
  "The Maw",
  "Snapped",
  "Aim Bot",
  "Space Captain",
  "Monoeye",
  "Hologram",
  "8ball",
  "Enraged",
  "Bot Boy",
  "What",
  "Black Belt",
  "Utter Shock",
  "Smiler",
  "Sticker Show",
  "TO BATTLE!",
  "Digitized",
  "High Accuracy",
  "Rainbow Clown",
  "Cat Fished",
  "Killa",
  "Visually Loud",
  "Kisser",
  "Froggie",
  "Squeakers",
  "Elf Shoes",
  "Air Krunker 4's",
  "SlideHoppers",
  "Krunkciago Kroks",
  "Who farted ?",
  "Bunnies",
  "Mi0 Boots",
  "Combat Boots",
  "Outlaw Boots",
  "LOUD Shoes",
  "The Welder Boots",
  "Ares Step",
  "Inhumane Boots",
  "Gatekeeper Walkers",
  "Boingggggg",
  "Pumpie",
  "Paper Airplane",
  "Pay Piggie",
  "Festive Flyer",
  "Hackusate",
  "Hollow Fade",
  "Frostlance",
  "Raynb0w",
  "Alter",
  "Sticky Situation",
  "Flamelurker",
  "W49B Gamma",
  "Forged",
  "Redux",
  "Dark Matter",
  "Cold-Saga",
  "Xingshi",
  "Neo Splatter",
  "Night Reaper",
  "AXX",
  "KU-NAI_DN",
  "Football",
  "KRPD Negotiator",
  "Marauders Cleaver",
  "Aether Haze",
  "2007forever",
  "MC Slappy",
  "Acid Razer",
  "Lumus",
  "Drakania",
  "MAGI",
  "Coldest Shard",
  "Shogeki",
  "Gifted Blade",
  "Celebration Bottle",
  "P1ckMe",
  "Clover",
  "Rotten Arm",
  "Pokie",
  "Heated Crowbar",
  "Volcanic Forge",
  "Chainsaw",
  "SACRED TOUCH",
  "Caretaker",
  "Slammer",
  "Jormungandr's Venom",
  "Antidote XVI",
  "Shuriken",
  "Soul Fang",
  "Despair",
  "Plasma Ball",
  "Galaxys",
  "Chain Blade",
  "Galagis",
  "Flamefang",
  "Void Slicer",
  "Psychofang",
  "Shuhei",
  "Plasma Dust",
  "Krypto Blade",
  "Volt Fang",
  "Dummy Grenade",
  "Mirror's Cutlass",
  "Captain Hook",
  "Model 24 Stielhandgranate",
  "Vandal",
  "Citizen's Arrest",
  "Fadecrusher",
  "Xenize",
  "Splasher",
  "Lollipop",
  "Phasma",
  "Tryptophobia",
  "Royal Turkey",
  "Kill Kount",
  "Virus",
  "Galamyth",
  "EL Cuchillo De la Muerte",
  "Poison Fang",
  "HOROLOGIUM",
  "Hail the night",
  "Plasma Cutter",
  "Remnant",
  "Trekina",
  "Hell's Butcher",
  "Bloodthirster",
  "Omega",
  "Quasar",
  "Amethyst",
  "Rusty Fire",
  "Molten Dagger",
  "Souleater",
  "Lunar Eclipse",
  "Marrowborne",
  "Present Basher",
  "Echoo",
  "Hero's Obelisk",
  "Hexodynamic",
  "Unguibus",
  "Emperor's Blade",
  "Silver Blade",
  "Master Blade",
  "Gold Blade",
  "Bronze Blade",
  "Diamond Blade",
  "Aromatic Blade",
  "Chunchunmaru",
  "Inquisitor's Cyberblade",
  "Bronze Cyberedge",
  "Silver Cyberedge",
  "Gold Cyberedge",
  "Diamond Cyberedge",
  "Master Cyberedge",
  "Demonic Wrath",
  "BladeLink-60",
  "Crystal Runes",
  "Kunaiz",
  "Stabby",
  "Toucaxe 2077",
  "CuttingEdge",
  "Tactical advantage",
  "KeepSafe",
  "Classic.",
  "futurism",
  "CLRBLD",
  "BWBLD",
  "Krunkiela 1",
  "Datakorder",
  "sTARZ2",
  "Dorange",
  "Dopler",
  "SmILe",
  "BaLl",
  "Cyber Alia",
  "Starduster",
  "Apprentice's might",
  "Legend's might",
  "Hero's might",
  "Superhero's smite",
  "Grandmaster's smite",
  "Joe's Dinner Knife",
  "LinkBlade-70",
  "DaggerLink-33.5",
  "Kama",
  "BEETLEJUICE",
  "Carnage friends",
  "Akkoro",
  "Nova",
  "Hackusate",
  "Izulu",
  "Izula",
  "Death Parade",
  "Demonic Haze",
  "Envious",
  "Stargazer",
  "Viva la Muerte",
  "The Oni",
  "Lurking Predator",
  "BitCrush",
  "Lovesick",
  "Neo Punk",
  "Angelic Fury",
  "Doomsday",
  "Raynb0w",
  "Baller",
  "Shattercore",
  "Pellucid",
  "Intervention VI",
  "Intervention XI",
  "EX7 Cybernetics",
  "M82",
  "Eliminator Mk.V",
  "Lunar Eclipse",
  "Venator tigris",
  "The New King",
  "Zhora II",
  "Ruinoid",
  "Longinus",
  "Exotica-S",
  "K.R.P.D Stalker",
  "DYSTO_P1",
  "DES Tychodyne 64",
  "Dracaena DSG",
  "AVENGER",
  "CelestialDragon",
  "Hana's Retribution",
  "Good Ol' Days",
  "Scout Mastery",
  "Kr-98",
  "Crowsnest",
  "LIT $MILE",
  "Hackusate",
  "Raynb0w",
  "EMPG Surge",
  "Agent Mastery",
  "Echelon-2",
  "Lunar Eclipse",
  "Luv is rage",
  "Brain Massage",
  "Prototype BWSX",
  "Hexgen",
  "Minttt",
  "Error 404",
  "Dracuo",
  "Hackusate",
  "Red Drago",
  "INHUMANE!",
  "Ultranoir",
  "Devourer",
  "Desert Bagel",
  "Hollow Matter",
  "OmuraZ-XY",
  "Abyssal",
  "Raynb0w",
  "Silenced",
  "Gelion MK 1",
  "MX-12",
  "Lunar Eclipse",
  "DesertHawk",
  "Desert hare",
  "Vulkan's Veagle",
  "Takao 11",
  "Hackusate",
  "Vroominator",
  "Raynb0w",
  "Cyberblast",
  "Maximum Boost",
  "Lunar Eclipse",
  "Cupids Blaster",
  "Prototype X-12",
  "Hackusate",
  "Raynb0w",
  "Bowman Mastery",
  "Cafe Lancer",
  "Lunar Eclipse",
  "LOVESTRUCK",
  "Gate to Hxll",
  "Woodstock",
  "LW-812",
  "Retro Mamaia",
  "Hackusate",
  "Worried Sick",
  "Worried ill",
  "Acid Devourer",
  "Infected Facility",
  "Raynb0w",
  "AUG",
  "HeatWave",
  "Lunar Eclipse",
  "Lucky Famas",
  "Hackusate",
  "Raynb0w",
  "C0b4lt",
  "Sonic Shotgun",
  "Lunar Eclipse",
  "Akaiittou VII",
  "Hackusate",
  "Buckshots",
  "Azashi",
  "Mane Attraction",
  "HI!*",
  "Raynb0w",
  "Present Danger",
  "CZ-75",
  "Lunar Eclipse",
  "ZOOTIEZ",
  "Fervid Spirit",
  "Krunk n Roll",
  "Galaxy Explorer",
  "Hackusate",
  "Raynb0w",
  "Blaster Mastery",
  "Lunar Eclipse",
  "Atomic Neutralizer",
  "Acid Howler",
  "Scarlet",
  "Apocalypse",
  "Futuristic",
  "Raiju",
  "Hackusate",
  "StremZ",
  "Kaiju",
  "AK Iris",
  "Grinchmas",
  "Tomb Nader",
  "Shroud of Fire",
  "Magnus",
  "Suetic at home",
  "Interspectrum 2.0",
  "Reality Warper",
  "Celestial Harvester",
  "CYBER&gt;RAGE",
  "My Boy",
  "Hunted",
  "Trouble and Mayhem",
  "Eye Candy",
  "Ghost Blade",
  "Ectoplasm",
  "Curse of Jormungandur",
  "1Ad-dA0",
  "Raynb0w",
  "Baller",
  "Pellucid",
  "Good Ol' Days",
  "City-47",
  "Lunar Eclipse",
  "Present Assault",
  "TGR-011",
  "AJ47",
  "Sanguine",
  "Vulkan's V2000",
  "Rezu",
  "Lordship",
  "Trigger Mastery",
  "VSS",
  "Eternal Flame",
  "Cyclone",
  "SharkByte",
  "Makeshift",
  "TA-97",
  "Volcano",
  "Hackusate",
  "Raynb0w",
  "Lunar Eclipse",
  "L-0-V-3.CANNON",
  "Alchemist",
  "KILLER.CANNON",
  "Pulse Reactor",
  "Hackusate",
  "Raynb0w",
  "Hackusate",
  "Zapuranium",
  "Raynb0w",
  "Hackusate",
  "Liberty",
  "Raynb0w",
  "Takanomei's Myth",
  "Hackusate",
  "Raynb0w",
  "Lunar Eclipse",
  "De-Humanizer",
  "Raynb0w",
  "Osiris' Servant",
  "Namazu",
  "Zrym",
  "Adrenaline",
  "LASEREDEMPTION",
  "Flash",
  "0v3Rload",
  "DESTINY",
  "Ceretta 92",
  "Glizzy .22",
  "Sel1609",
  "Catgirl",
  "Lunar Eclipse",
  "1911",
  "Good'ol'Pistol",
  "WildClaw",
  "Bahamut",
  "Hackusate",
  "Oldie",
  "Aurora Tribe",
  "Grand",
  "RED//OMEGA",
  "Authority",
  "x0n-voX",
  "Raynb0w",
  "Baller",
  "Exo-Skeleton",
  "MP5",
  "Neko-90",
  "Pink-90",
  "Escorpio",
  "Barebones",
  "veccy!",
  "Bunny Gun",
  "Good'ol'Smg",
  "Bloc97",
  "Bizon",
  "Gumballer",
  "Cataclysm",
  "Frontliner",
  "Lunar Eclipse",
  "Flame Tamer",
  "Hackusate",
  "Holsu",
  "T.H. Cyber Covenant",
  "Chromatic Penta",
  "Sea Wanderer",
  "Raynb0w",
  "Baller",
  "Detective Mastery",
  "Cryogen III",
  "Helios M2",
  "Lunar Eclipse",
  "Snubby",
  "ARISAKA",
  "Pellucid",
  "Woodstock",
  "Raynb0w",
  "Hackusate",
  "Toshiko",
  "TRESPASSER",
  "Imperial Ice",
  "Wrath",
  "Vince Mastery",
  "Good Ol' Days",
  "Hateful Flesh",
  "Old Trusty",
  "Lunar Eclipse",
  "The Mighty Gobbler",
  "Overgrown",
  "Revolving Shotgun",
  "Tavor SG",
  "Type A",
  "Hackusate",
  "Centibeast",
  "The Dragon's Legend",
  "Nefertiti",
  "Awaken Flame",
  "Raynb0w",
  "Good Ol' Days",
  "Atlas Guardian",
  "AEK-999",
  "Prism",
  "TSH Type 105",
  "Chauchat",
  "Lunar Eclipse",
  "Stocking Stuffer",
  "Hackusate",
  "Gemstone",
  "Discoblaze",
  "Raynb0w",
  "Marksman Mastery",
  "SAR-502",
  "Lunar Eclipse",
  "Bondsman",
  "Hackusate",
  "Raynb0w",
  "Broadside",
  "SMAW",
  "Lunar Eclipse",
  "Coffin Cannon",
  "Egg Launcher",
  "Froge",
  "Krunkette 1",
  "Rolled",
  "Krunk Twerk",
  "KR Minion",
  "True Strength",
];

export const relic_labels = [
  "Danger Ahead",
  "Walker Stalker",
  "Captain's Pride",
  "Lost souls",
  "First Watch",
  "Bot 1",
  "Bot 2",
  "0w0",
  "Sussy Headset",
  "Future Artifact",
  "Dimension Shifters",
  "TSTNG",
  "Oscilloscope",
  "o_o",
  "Boom Boxer",
  "Splinter",
  "NVD",
  "Puppet Master",
  "Jason",
  "Seefood",
  "Googly",
  "Soulless",
  "Soul Eater",
  "Blockhead",
  "Deadball",
  "Anti-hero",
  "Lil Jack",
  "Balloon",
  "Necromancer",
  "K.P.D Hat",
  "Lieutenant",
  "Pumpking",
  "Re-tron I",
  "Re-tron II",
  "Q-tron I",
  "O-tron I",
  "Confuse-Tron",
  "Fabulous-Tron",
  "Hazmat",
  "Scientist",
  "Umbrella",
  "Methane",
  "Toxins",
  "Cuppa",
  "Propeller Cap",
  "C4-head",
  "Bomber",
  "High",
  "Sir Krunk V",
  "Ancient Eye",
  "Swarm",
  "Love Bug",
  "Genius",
  "Samurai",
  "Dark Samurai",
  "Cyburai",
  "Burning Ronin",
  "Conscience",
  "Night Doctor",
  "Plague Doctor",
  "Bubonic",
  "Ice Doctor",
  "Don't Jinx it",
  "Clause",
  "Skrok Antlers",
  "Meme Master",
  "BaDaby",
  "Gnomer",
  "Helm of the Husky",
  "HIZ-001",
  "Bad Habits",
  "Krimps",
  "PC Tron",
  "Oni",
  "Onichad",
  "Mark of the Tigress",
  "Rainbow Lover",
  "Rune Decipher",
  "Warn!ng",
  "Dont Sue Us",
  "Extremely Loud",
  "Gambler",
  "Laptop Tron",
  "Fancy-Tron",
  "Sleepy-Tron",
  "Giant",
  "Toy Planes",
  "Destroyer",
  "Merg",
  "WeeeWoooo",
  "Sheriff",
  "Gingerbread",
  "Krypton Head",
  "Xenon Head",
  "Aurum Head",
  "Ceaser",
  "Iron Overlord",
  "Bandit",
  "Arrowhead",
  "Highland",
  "Workplace accident",
  "Toilet master",
  "Unstoppable Force",
  "Blunt Force",
  "Haunting Box",
  "Angelic Guardian",
  "Tv Tron A",
  "Tv Tron B",
  "Tv Tron C",
  "Tv Tron D",
  "TV Tron LCD",
  "TV Tron HD",
  "Forever Glasses",
  "Vulkan's Helmet",
  "Joe's Hat",
  "Mi0 Helmet",
  "Gloriou Pompadour",
  "Psychedelic",
  "Acidic Nerves",
  "Cyber Visor",
  "Missing Texture",
  "Alpha",
  "Eridion",
  "Prem",
  "Download failed",
  "Dicey Situation",
  "Plazman",
  "Krunkie",
  "Slayer Crown",
  "Z-Core",
  "Snowman Head",
  "2023 Glasses",
  "Love Beanie",
  "Lucky Hat",
  "Carroperator",
  "Good'ol'Mask",
  "Infected",
  "Scoped in",
  "X-Tron",
  "Razza",
  "Chillin",
  "Dizzy",
  "Camper",
  "Bag it up",
  "Flathead",
  "Task Force",
  "Captain Salmon",
  "Pharaoh",
  "Messy",
  "Bandito",
  "Chosen One",
  "Acid Reaper",
  "Soul Reaper",
  "Undead",
  "Krystal",
  "Blood Krystal",
  "Christmas Lights",
  "Chocolate",
  "Precious Egg",
  "Frog",
  "Circuits",
  "Muffler",
  "Season 6 Heroic Ticket",
  "Playercard Ticket",
  "Season 7 Heroic Ticket",
  "Demonic Wings",
  "Diablo Wings",
  "Psychedelic Wings",
  "Forever Shirt",
  "Digilord",
  "Honed Gold",
  "Rainbow Swirls",
  "Pokerface",
  "Lover",
  "Puzzler",
  "Jet Backpack",
  "Gradient Pennon",
  "Shatter Wings",
  "Torn Aileron",
  "Krypton Body",
  "Xenon Body",
  "Aurum Body",
  "Sussy Carrot Body",
  "LBM Cape",
  "Joe's Overall",
  "Mi0 Armour",
  "Pompadourian Vest",
  "V-Drive",
  "Plazma Chest",
  "Bullet Loop",
  "Z-Core Radio",
  "Always Watching",
  "Slayer Plate Armour",
  "RGB Chest",
  "Cubez",
  "Love Top",
  "Lucky Top",
  "Carroperator Vest",
  "Good'ol'Vest",
  "Infected Body",
  "Gatekeeper Tanktop",
  "AI Takeover",
  "AI",
  "Automatis",
  "Snowglide",
  "Circuitized",
  "Scroll",
  "Angry",
  "Gold N' Egg",
  "Agares",
  "Angelic Wings",
  "Parade Poncho",
  "Night Predator",
  "Krum Cape",
  "Krunkmas Cloak",
  "TTV Cape",
  "Zero Ground",
  "Just Hanging",
  "Arunasura",
  "Barong",
  "Cheerfull",
  "Holiday Cheer",
  "Tentacle",
  "Disco Shirt",
  "Starlight",
  "Robo Wings",
  "Boosters",
  "Mechacrow",
  "Dynocrow",
  "Magic Book",
  "Papilion",
  "Morpho",
  "Nano Wings",
  "Stream Suit",
  "Dusty",
  "Cocoa",
  "Woodland",
  "Cotton Candy",
  "Mood",
  "Sandy",
  "Sugarbear",
  "Pastell",
  "Slender",
  "Zombie",
  "Strongman",
  "Carotine",
  "Crimson",
  "Lavender",
  "Terra",
  "Amberite",
  "Coldsnap",
  "Ghast",
  "Devious",
  "Mankini",
  "Censored",
  "Banana Tail",
  "Moonflyer",
  "Potted",
  "Gunslinger",
  "Maid's Skirt",
  "Krypton Waist",
  "Xenon Waist",
  "Aurum Waist",
  "Forever Kilt",
  "Stardust glider",
  "Vulkan's Legs",
  "LBM Belt",
  "Joe's Utility Belt",
  "Beltium",
  "KRPD Utility Belt",
  "Outlaw Gadgets",
  "Plazma Belt",
  "Slayer Belt",
  "Serpent Legs",
  "Toadstool",
  "Walpurgis",
  "Lil Guy",
  "Lost Signal",
  "Z-Core Plate",
  "Ready to Celebrate",
  "Love Belt",
  "Lucky Belt",
  "Inhumane Belt",
  "Gatekeeper Belt",
  "Racer",
  "Smooch",
  "Creepy Crawly",
  "Exhausted",
  "Grumpy",
  "Haunted",
  "Krunked",
  "Sassy",
  "Dashing",
  "The Chad",
  "Third Eye",
  "Grizzled",
  "Lil Krunk",
  "Mime",
  "Malcolm",
  "Lonely",
  "Googly",
  "Fishy",
  "AimBot",
  "Nodding",
  "Fire Bender",
  "Capt Krunk",
  "Creep",
  "Impish",
  "Uncanny",
  "Night Stalker",
  "Killer Clown",
  "Sorry",
  "Sweaty",
  "Whip Me",
  "Yummy",
  "The MegaChad",
  "Absolutely Pissed",
  "Cringe",
  "High Beam",
  "Sussy",
  "Oh Yeah",
  "Growl",
  "Shaman",
  "Warrior",
  "Brain Freeze",
  "Mmm",
  "Nerdy",
  "Hot Headed",
  "Crazy Larry",
  "Happy Hearts",
  "Constipated",
  "It",
  "Psycho",
  "Uh?",
  "Tiger",
  "Baked",
  "Sugoi",
  "Zen",
  "AI",
  "Dead zone",
  "Petrified",
  "Tunnel Vision",
  "Hot Shot",
  "Sleepy Chinner",
  "Radical",
  "Stone Cold",
  "The Doomer",
  "Gumz",
  "Glubi",
  "Miss Flower Power",
  "Meow Heart",
  "Alarm Activated",
  "Tribe Pretty",
  "Bring It",
  "Globi",
  "Jolly",
  "Dr Monk",
  "Mob Boss",
  "I'm Fine Dude",
  "King of Krunk",
  "Sherlock Holes",
  "Peekaboo",
  "Brain Eater",
  "Happy TeeVee",
  "Krunkuna",
  "Secretary Krunkuna",
  "Alt Krunkuna",
  "Angry Fella",
  "Angry Hero",
  "Dr.Mainframe",
  "Wasted",
  "Chew Zone",
  "Amazed",
  "Confidence",
  "Krunkasso",
  "Not enough content",
  "Browman",
  "Sci-fry",
  "Cartoon",
  "Upset",
  "Bloodrushed",
  "Eye Laser",
  "Unbelievable",
  "Even more Unbelievable",
  "Cybo",
  "Tribal",
  "Silly Boy",
  "Bruh what is this face",
  "Natural Zoom",
  "1Head",
  "Frosty Beard",
  "Sir Gentleman",
  "Sly Glasses",
  "Augmented",
  "Bounty Hunter",
  "Eddrido",
  "Outlaw Brainiac",
  "Say Cheese",
  "No Comment",
  "Please Don't Backfire",
  "Dental Plan",
  "Tiny Rage",
  "Walrus",
  "Shades",
  "Moist",
  "Red Dot",
  "Orcish",
  "Lil' Vince",
  "Saw a Bigger Bug",
  "Red Zone",
  "Slippery Slope",
  "Employee of the Month",
  "Buck the Teether",
  "Watcher",
  "Charmer",
  "Broken",
  "Devilish",
  "Perfect Teeth",
  "Eagle Eyes",
  "All Smiles",
  "Fan Language",
  "Thug Life",
  "Mono Cutie",
  "Something Fishy",
  "Krunker98",
  "Gatekeeper",
  "Raider General",
  "Raider Goon",
  "Cyborg",
  "Hobo",
  "Monobrow",
  "Krunkdashian",
  "Anticipation",
  "Angry Chef",
  "Angry KRUNKsketch",
  "Voodoo",
  "Angry Depressy",
  "Paranoid",
  "Trance",
  "Bad Eye",
  "Good Eye",
  "Big Teeth",
  "DownUnder",
  "Yas Queen",
  "Hangry",
  "Gob Stopper",
  "Sleepless",
  "Tripping",
  "Tasty",
  "Whormhole",
  "Lets Go",
  "Swamper",
  "Me Like",
  "U Mad?",
  "Beaten",
  "Content Clown",
  "Shell Shoked",
  "Blind Doc",
  "Mr Clause",
  "Flappy",
  "Grinch",
  "Big Head",
  "Frosty",
  "Bun",
  "Joe's Face",
  "Red All Stars",
  "Blue All Stars",
  "Krunkstar",
  "Ember Slides",
  "Charity",
  "Forever Shoes",
  "Pepe Slippers",
  "Apollo",
  "Santa's Boots",
  "Safety Boots",
  "Buckled up",
  "Dainty Shoes",
  "Krypton Shoes",
  "Xenon Shoes",
  "Bunny Shoes",
  "Aurum Shoes",
  "Red Killers",
  "Plazma-Walkers",
  "Z-Core Boots",
  "TV Tron Slides",
  "Slayer Plate Boots",
  "Krockets",
  "Love Shoes",
  "Lucky Shoes",
  "Carroperator Boots",
  "Good'ol'Boots",
  "Bucket",
  "Goop",
  "Ice Skater",
  "Stompers",
  "Peg",
  "Racer",
  "Unicorn Slippers",
  "Dusk Fang",
  "Samurai Sword",
  "Red Reaper",
  "Retro-Slicer",
  "Kaartana",
  "Cold-Blooded",
  "Red Card",
  "Combat Banana",
  "Mic'd Up",
  "Macuahuitl",
  "Bloodless",
  "Watch",
  "Predator",
  "Charl",
  "Flintstone",
  "Kinto",
  "Divine",
  "Diabolo",
  "Fang of Coatl",
  "Dragon's Eye",
  "Mamba",
  "Festive Wand",
  "Mallet",
  "Cast Iron",
  "Baton",
  "Cane",
  "Steelfang",
  "Zvilpogghua",
  "Volcanic",
  "Cyberclaw",
  "Tellkario",
  "T.7-CRASH",
  "Echo Fang",
  "Acid Claw",
  "Sundae Slicer",
  "Kanav",
  "Just Slicing",
  "Aziru",
  "Sweet Tooth",
  "Cutlass",
  "Vase",
  "Meaty's Cleaver",
  "Kunai",
  "HeatSeeker",
  "Tropical Ripper",
  "Airhorn",
  "That's a Knife",
  "Cracked Punk",
  "Galaxy Flow",
  "Sweet Stab",
  "Tiger Knife",
  "Cyberslash",
  "Sl4s-3R",
  "Scorcher",
  "Flesh Crystal",
  "Venomous Stab",
  "Incendiarism",
  "Lady Luck",
  "Cyber Retro",
  "Alaksa",
  "Plated Damascus",
  "420",
  "Romanov",
  "Neptune",
  "Rainsickle",
  "Fadeliner",
  "WHAT",
  "XG-2205",
  "Constellation",
  "The Sanguine Harvest",
  "Zima",
  "Te Pania",
  "Remote Control",
  "Wow",
  "Wrench",
  "Sharpened Crab",
  "Emerald Splash",
  "Poom",
  "Workin",
  "NeoBlossom",
  "Doin",
  "Blossommmm",
  "Peppermint Piercer",
  "Screwy",
  "Aurum",
  "Venomous Twist",
  "Twisted Lightning",
  "Kitani",
  "Sacrificial Dagger",
  "Sarius",
  "Cursed Bones",
  "Magical Girl",
  "Krum Juicer",
  "Skeletal Remains",
  "Christmas Cutter",
  "Stabby Water",
  "Carambit",
  "Egg basket",
  "Carrotana",
  "Take A Bite",
  "ODM",
  "Teknika-Blade",
  "Clean Cut",
  "Cyber Slayer",
  "SPR-Blade",
  "Blade 23",
  "Ballistic Knife",
  "Crimson Edge",
  "Vectronus",
  "Incrementum Aliena",
  "Flame Viper",
  "Red Phantom",
  "Magma Core",
  "Daimyo Spirit",
  "24-Jul",
  "Sheikah",
  "Verb",
  "BunnyBeam",
  "Hakan",
  "Wildstyle",
  "Neon Reaver",
  "Moon Juice",
  "Cyber Midnight",
  "Rezein",
  "Radalive",
  "Sekigahara",
  "Sentinel-56",
  "Steel Serpent",
  "Theta Republica",
  "Resurrection",
  "Bopper",
  "Containment",
  "Tedssyt",
  "AWP Pacemaker",
  "Automaton",
  "Arcturus",
  "Annihilation",
  "Wasteland Warrior",
  "Astral Horror",
  "Underworld Worm",
  "Reinga",
  "Vespidae Mk. III",
  "Polar",
  "Sea Devourer",
  "Necron Bolt",
  "Night Time Terror",
  "Captain Scar Face",
  "Unravel",
  "Neon Dreamer",
  "Space Ranger",
  "City's Gate",
  "Nav",
  "Void Odyssey",
  "Ghost Devourer",
  "Twisted Dragon",
  "Inverse",
  "Recko",
  "Dragon Dimension",
  "Momo",
  "Primary",
  "Diamond Fibre",
  "Nirmiti",
  "Stang",
  "Nocturno Mk.2",
  "Hound of Hell",
  "Pace Dore",
  "Shinji",
  "Viole",
  "Santa's Factory",
  "Aria",
  "Fragment",
  "Iron Assault",
  "Cybertigger",
  "Jaw Ripper",
  "Evo-S2K2",
  "Melted",
  "STM-PNK",
  "The White Queen",
  "Xenodized",
  "Twin Howl",
  "Salvaged Smiles",
  "The Emperor of Atlantis",
  "Forever Hunting",
  "Hexo-Hydrophobic",
  "Galactic Odyssey",
  "Comic Striker",
  "The Tenth Galaxy",
  "Razor",
  "HUE&gt;RAGE",
  "Fierce",
  "Strawberry Milk",
  "Undead Champion",
  "Beholder's Eye",
  "V^V",
  "TAKE ME BACK",
  "Delicious Love",
  "Pick Me",
  "Lore",
  "The Danger",
  "The Risk",
  "Reaver",
  "Gluttony",
  "Retrix",
  "Dreamr",
  "La Muerte",
  "The Cerberus",
  "Splixen",
  "Eagle Strike",
  "Lost humanity",
  "AWP Stream",
  "AWP Dazzle",
  "Octodance",
  "Ice Fade",
  "Just Vibing",
  "Uzera",
  "Grapegun MK2",
  "Softie",
  "Bee-zi",
  "CHIMERA",
  "Fade Fuze",
  "Pulse",
  "Fairytale",
  "Overpixelated",
  "Idcn",
  "Mili",
  "Digi-Traveler",
  "Meow :3",
  "Charoite",
  "Lifeline",
  "Ghastly Predator",
  "Overclock",
  "Electroshock",
  "CASLE",
  "Chrgdup",
  "Class Zero",
  "Pinku Attack",
  "Code Red",
  "Vandalized",
  "Ancient Guardian",
  "Abominable",
  "Neo Flamma",
  "Defender",
  "Hacker Tagged",
  "Hot",
  "Game Changer",
  "Runic",
  "Ganbatte",
  "Machina",
  "Aikon",
  "Xena",
  "Captain Octo",
  "Captain Red Eye",
  "Sanctum",
  "soitsu",
  "Z3AGLE",
  "Railix V",
  "Simax",
  "Kami No Masuku",
  "Prosperity Dragon",
  "Hue Fever",
  "Kanagawa King",
  "Casteris",
  "Sherbet Blast",
  "Saib",
  "Crimson Valence",
  "Dusty",
  "Organic-02",
  "Goated",
  "Kristo",
  "Cyber-Kill Ghost",
  "Umbral Harvest",
  "Neon Love",
  "Alpha",
  "Kill King",
  "Void's Gluttonous",
  "Phosphorus",
  "Kitani",
  "Nightlight",
  "Tsundeagle",
  "Galati-S",
  "Incarceum",
  "Mega Heat",
  "Stryder",
  "Koltron X",
  "Xhorun",
  "Artifact XY",
  "Overloaded",
  "Proton XV",
  "HELL",
  "HEAVEN",
  "The Chosen One",
  "Dream Destroyer",
  "BLKStripe",
  "E-12",
  "Rocket Jet",
  "Wraith",
  "Black N' Gold",
  "Fabianero",
  "Classified",
  "Mayan's Light",
  "Celestrofeo",
  "Shocking Strike",
  "Sorcerer",
  "Vinyl",
  "Doomsday",
  "Energizer",
  "Scaze",
  "Azeal",
  "Synthetic Void",
  "Anky",
  "Sentry",
  "Izon",
  "Entry to Heaven",
  "FMS-08",
  "PORTAL_XC7",
  "Hawkmot-4",
  "Enter The Hxllxw",
  "Medic",
  "Vibrant Burst",
  "Dancheong",
  "CHAOS",
  "ALIEN X",
  "Mindseeker",
  "Chlorine Injection",
  "Come Back",
  "Porcelain Tigress",
  "Kumori",
  "KAVO-K 10",
  "KAVO-K 20",
  "FMAS MKii",
  "Structured Data",
  "Blockstream",
  "Keniro PD",
  "Fidelis",
  "Shocker 2000",
  "Verde",
  "MEOW",
  "Fluorish",
  "KRZ-Y",
  "Quadra",
  "Data Bank",
  "Kaligator",
  "Galaxy Morse",
  "Fire Storm",
  "Frosted",
  "Samurai Spirit",
  "Botanical",
  "Wyvern",
  "Forbidden",
  "Draco",
  "MUGSHOTTY",
  "Double TNT",
  "Pip Squeak",
  "Hexamerald",
  "Shape",
  "heavy metal",
  "Passion",
  "Cosmos Hunter",
  "1974",
  "Line Hunter",
  "Winter Delight",
  "Fertul",
  "Hexabyte",
  "Cadaver",
  "0LD D4YS",
  "K-Racer",
  "gL!tcH3d",
  "Big Mouth",
  "cyalater",
  "Omura-X",
  "Nyaniac",
  "Vendy",
  "Candis",
  "Cooligan",
  "Urus",
  "Legend",
  "Organic-01",
  "Majesty",
  "09-Oct",
  "KanjiPD",
  "Dsh",
  "Trnsprt",
  "Blue Flax",
  "Cyberize",
  "Avalanche Spirits",
  "RCER2022",
  "ALTRCER",
  "Greenlin",
  "Pixie",
  "PowerCell",
  "REVAMPED",
  "Security-KR7",
  "Th3 Numb3rs",
  "Jet-RX88",
  "BE YOU",
  "Dust",
  "Elemental",
  "APX",
  "Wasteland Smile",
  "Microwaver",
  "C-300",
  "Freight-14",
  "Coldheart",
  "Cestis",
  "Logistikks",
  "Forseti's Essence",
  "Fyefighter",
  "Z-202",
  "Pentacore",
  "Eco",
  "The Zapper",
  "Hypnotic",
  "Oioo",
  "Zapp Meister",
  "Mizoist",
  "Paladin",
  "Krunk Punk",
  "Gehenna",
  "Sleigh Ride",
  "Blast",
  "Time Tracer",
  "C-419",
  "Void",
  "Lightning Storm",
  "Scorched",
  "Urban Splat",
  "Lunatic",
  "Lunar",
  "Insanity",
  "Diode",
  "Outrunner",
  "Draconic",
  "HyperYolk",
  "Neon Ripper",
  "Sagittarius",
  "Fragternity",
  "Ifrit",
  "Komics",
  "Swarm",
  "Letos",
  "Machinehead",
  "Plague",
  "Frostywolf",
  "Mosasaur",
  "Milestone",
  "Twitcher",
  "caL",
  "Cryptic J",
  "Overseer",
  "Etona",
  "NeoTitan",
  "Full Moon",
  "Nightmare",
  "Crimson",
  "Corruption",
  "Onamu",
  "Celeste",
  "Flow",
  "Freshmint",
  "Lykos",
  "Ion X",
  "Nav",
  "Lore",
  "Plasma Rifle",
  "Epitome",
  "Synergy",
  "All Aboard",
  "Mecha Zone",
  "Ancient Rave",
  "Lazor",
  "Nuclear Winter",
  "Sentient",
  "RabbidTurkey",
  "Decimator",
  "DeathBeat",
  "Circuit",
  "ZenDrive",
  "Ashen Ice",
  "Bombs away!",
  "Z3D",
  "Spirit of the Inferno",
  "City Defender",
  "Acidwire",
  "Necromatic",
  "TP-1502",
  "Vkingrev",
  "RiotAlexis",
  "Kizza",
  "Дpyг's Lore",
  "Sorable IV",
  "Serpent of Summer",
  "Moondrake",
  "Drizzy",
  "1NN3R D3M0N5",
  "Regeneration",
  "Depth Crawler",
  "F1-47",
  "Cyb3r_Le0",
  "004-3RrOR",
  "Tripwire",
  "FineLine",
  "LM-21",
  "Resonate",
  "Warden Of Time",
  "Cyber Bull",
  "Familia",
  "Wasteland Factory",
  "Wakeup",
  "Demonic-47",
  "Tigracer",
  "Icarus",
  "CHAOS+CONTROL",
  "Starface",
  "The Black King",
  "Duke",
  "Kltta",
  "Kltto",
  "Hyper Town",
  "Yonkers",
  "StarTravelers",
  "Transformo-Z",
  "Transformo-X",
  "Pointman Overdrive",
  "Unyielding Hero",
  "Cursed Phoenix",
  "Cyber Flower",
  "Akolor",
  "X-23",
  "Big Spook",
  "BOB.",
  "Almost Real",
  "Stallion",
  "BLAHHHHH",
  "Hot Mist",
  "Out of this world",
  "Wasteland Smile",
  "Temple of Wrath",
  "Rave It",
  "Gulu",
  "Happy 2023",
  "SuperAK47",
  "Finisher",
  "G000P",
  "Zubek",
  "Heart47",
  "Ripper",
  "Exodus",
  "Reaper's Madness",
  "Reconstruction Imminent",
  "Plated Gnasher",
  "SuperAK47",
  "AK Mortal",
  "Quacker",
  "alt",
  "Rabla 2050",
  "Hive",
  "Wire",
  "Envy",
  "T9-Lime",
  "Aquarius",
  "The Justice",
  "Poisonous",
  "Portal Breaker",
  "SUNSDEATH",
  "BO$$",
  "Hornet",
  "The 2",
  "GRENN",
  "Fire Shock",
  "Tiger Shock",
  "Poisoned Lily",
  "CHAOS GIRL",
  "M3OW",
  "CZ500",
  "Dual",
  "exile",
  "bluee",
  "CHRG",
  "Hexabyte",
  "Z-8080 S",
  "Ectoplasm",
  "Thunder Serpent",
  "Royal Dragon",
  "Diamond Back",
  "RTF",
  "X-PLSMA",
  "Space Panda",
  "Gun Point",
  "Bulldozer",
  "Dragon's Realm",
  "Mimi",
  "Destrosimov 007",
  "Lead Dispenser",
  "Trapped Ghouls",
  "Federation Z",
  "USPSTEAM",
  "My Little SLAYER",
  "WireStation :D",
  "Limant",
  "Huangdi",
  "Mecha-POP",
  "Shes",
  "EarfQuake",
  "ELF",
  "WACKYDEATH",
  "Blizzardious",
  "TEKNIKA",
  "LineArt",
  "Widowmaker",
  "Biohazard",
  "Stealth Pull",
  "Shadow",
  "Warden",
  "Dragon Breath",
  "Otzarreta",
  "Wychwood",
  "Composite",
  "Vandal",
  "Hellhound",
  "Voyage",
  "Overwatch",
  "Graffitius",
  "Cinder",
  "Reactor",
  "Saberstorm",
  "Rapid Plasma",
  "Mecha's Bane",
  "Dark Soul",
  "VoidMatter",
  "Smiley",
  "Cyberdragon",
  "CandyLand",
  "Embers",
  "Warp Sequence",
  "Heaven Protocol",
  "Frowny",
  "Carcinogen MK. 6",
  "Cyborg Pigeon",
  "XO",
  "Buksa",
  "Frostburn",
  "Blossom Fusion",
  "Triangle Madness",
  "Digi",
  "Fierce Spirit",
  "Tigadelic",
  "Carousel",
  "Physs",
  "Energized",
  "Binary Creature",
  "Cybershield",
  "Mecha Ion",
  "Unit 77",
  "GLOBL.",
  "POPPER!",
  "Glowbug",
  "Forsaken Warrior",
  "HOLaunch",
  "ChargedX",
  "Cyber Sun",
  "Dracuo Litch",
  "Mecha Bunny",
  "Cybertron",
  "0LD D4YS",
  "Killing Machine",
  "Captane",
  "Redolent",
  "Symbiote",
  "Fire Starter",
  "Component-06",
  "0vercharged",
  "FrostBound",
  "Terminat-R",
  "Rev 2068",
  "Dark Aether",
  "FadeLock-004",
  "Esfinge",
  "Cauldron of Souls",
  "Ruling the Realms",
  "Time Relic",
  "Sunsettia",
  "Cyanix",
  "Tyg-R-24K",
  "Rev 2078",
  "Golden Nemesis",
  "Blixt",
  "Cyber Config",
  "WINNR",
  "Protector Of the Night",
  "Compact-88",
  "Intern-90",
  "Screentone",
  "Radioactive",
  "Redstream",
  "EXITVIDA",
  "Spectre Flow",
  "Wingman",
  "Hyp-R",
  "Gridwalker",
  "Spacer",
  "Vandal",
  "Steampunk REV",
  "Nordic",
  "Flame Talon",
  "Orchid Dream",
  "Luminous",
  "Absinthe",
  "Scoria",
  "Krunkitis",
  "Crystallize",
  "Neuromance",
  "Outrunner",
  "Insidious",
  "Bloodhound",
  "Cybergum",
  "Dojo",
  "Toxic Drip",
  "Arkam",
  "Dragon's Mark",
  "Chrombine",
  "Krunkshots",
  "Petal Dance",
  "Molten Core",
  "Breach N' Clear",
  "Forgotten",
  "Toxi-city",
  "Cytek-KRNK",
  "R3d",
  "Deathshot",
  "Or4ng",
  "8lu",
  "CUT3-XM",
  "Ravenia Mk.1",
  "Cyber Ferret",
  "Kinabalu",
  "Super Werewolf",
  "Multi-Core",
  "Tropical",
  "Mounder",
  "AAA Powerline",
  "duke",
  "Ciel",
  "TechMaze",
  "Copper Wireframe",
  "Edgekrunker",
  "Evil",
  "Moonlight",
  "Lineride",
  "Adventurine",
  "Surreal",
  "Crystalline",
  "Sunburst",
  "Santa's Anarchy",
  "Iron Patriot",
  "EQ-9 Decimator",
  "Rally",
  "ETX-8 RGB Edition",
  "Breach",
  "Aftermath",
  "Gorosei",
  "Loperamix",
  "X-Shocker",
  "Greek MythoLMG",
  "Jewel Mozaik",
  "Last AID",
  "Z-1405",
  "Tiger's Wrath",
  "Heavy Plasma",
  "Gunmetal Circuit",
  "The Big-Dozer",
  "Star Powder",
  "Kaptain K",
  "Spook!",
  "Underwater",
  "DeadShot",
  "Confetti",
  "Apocalyptic Neo Punk",
  "Mercury",
  "WARBOY",
  "Bloodbath",
  "Injection",
  "Tartrazine",
  "Diopside",
  "Egg Hunt",
  "MMA Plasma",
  "Wispering Woods",
  "Xethes",
  "Rufino",
  "Behemoth",
  "Dracrunic",
  "KR-DR1FT",
  "Lava Bender",
  "SQUAREHEADS",
  "Bubblegum",
  "Royal Paladin",
  "Neon Tigress",
  "Cyber Mov",
  "Cyber Abyss",
  "Patina",
  "Sea Foam",
  "Tidal Swarm",
  "Exo-Carnage",
  "Hellsman",
  "Necromancer's Skull",
  "Thunderstrike",
  "Lepton",
  "Aries",
  "Retro Beast",
  "Ciote",
  "Guardian",
  "Galactic Ranger 3000",
  "Plasma Nuke",
  "Lightning Strike",
  "IronDwarf",
  "Triple Threat",
  "Dynamite Launcher",
  "Explosive Haircut",
  "Kork Launcher",
  "Frosted Bite",
  "Kill Feed",
  "S.A.R",
  "EZ",
  "A",
  "E",
  "Just Vibing",
  "All Hail Checkmark",
  "Life Changer",
  "Eyebrows",
  "Chalk 'em up",
  "KReature",
  "The Void",
  "The Equalizers",
  "The Marksman",
  "KrunkPunk",
  "Sigil of Hope",
  "Target Locked",
  "Krunkette 2",
  "Playmat",
  "Anti-cheat",
];

export const legendary_labels = [
  "Kanji",
  "Warp",
  "Statues",
  "Meat Market",
  "Pullin' Up",
  "Mommys Money",
  "Mood 2.0",
  "Vibin",
  "Abyss",
  "Moon Lander",
  "Riot's Bloom",
  "Swonky",
  "Duck Hunt",
  "Red Digital",
  "Blue Digital",
  "Purple Digital",
  "Orange Digital",
  "Green Digital",
  "Pink Digital",
  "Gruelling Grind",
  "Final Stand",
  "Alien Microbe",
  "Officer Buddy",
  "Ghostly Cowboy",
  "Bane",
  "Raccoon Cap",
  "Santa",
  "Sicko",
  "Succubus",
  "Devil Horns",
  "Gentle Beast",
  "Kraken",
  "Socket",
  "Puff Puff",
  "Skull Mask",
  "Acid Skull",
  "Amber Skull",
  "Stein",
  "Moneybags",
  "Gobbler",
  "Mr Doodles",
  "Drowned",
  "Demon Baby",
  "Krunkuto",
  "5Head",
  "Papa",
  "Building",
  "Caked",
  "Optic",
  "Spock",
  "Miss Package",
  "Box Head",
  "Budget TV",
  "NARCISSIST*",
  "Presented",
  "Clueless",
  "Innocent",
  "Warlock",
  "Bakuretsu",
  "Jester",
  "Fool",
  "Ninja Mask",
  "Pickler",
  "Candy Caney",
  "Membi",
  "Lemy",
  "Limey",
  "Shroomy",
  "Bane",
  "Halo",
  "Loud",
  "Mysterious",
  "Watchful",
  "Grizzly Hat",
  "Bear Hat",
  "Hat Hat",
  "Baby",
  "Sir",
  "Lady",
  "King",
  "Queen",
  "Face Shield",
  "TECH Shield",
  "Mossworm",
  "Science Kid",
  "TechWear",
  "Noodler",
  "Black Bunny",
  "Grey Bunny",
  "Pink Bunny",
  "Galaxy Bunny",
  "Punk Bunny",
  "Red Buddy",
  "Green Buddy",
  "Panda King",
  "Avo",
  "Piper",
  "Robot Helmet",
  "Santa",
  "Reindeer",
  "Ahoy",
  "Cat Headphones",
  "Panda Headphones",
  "Knight Helmet",
  "Hip",
  "Birb",
  "Race Helmet",
  "Jester Hat",
  "Demon Hood",
  "Altyn",
  "Verified!",
  "Fake Partner",
  "Fake Premium",
  "Promise Ring",
  "Checkmark from Wish",
  "Trendy Biker",
  "Cybercat Ears",
  "Skribble Face",
  "Golden Crown",
  "Creamer",
  "Bottle Capper",
  "Toasted",
  "Muncher",
  "Octo",
  "Master Drinker",
  "Krayon Bandit",
  "Capricorn Horns",
  "Bull Horns",
  "Deer Horns",
  "Fake Nose Glasses",
  "Pig Head",
  "Eliminator III",
  "3D glasses",
  "Orc",
  "Beluga",
  "Mr Krabs",
  "Undead",
  "Cyber-zombie",
  "Wattle",
  "Festive Hat",
  "Maid's Bonnet",
  "AA Defense",
  "Clock",
  "Jack O' Lantern",
  "Radar",
  "Pro-go",
  "Ravager",
  "Unforseen Evil",
  "Caked up",
  "Pinocchio",
  "Gear-Pods",
  "Mailbox",
  "Pink Bunny-Hat",
  "Green Bunny-Hat",
  "Brown Bunny-Hat",
  "Maintenance",
  "Eel",
  "TTV Tron",
  "Krunk TTV",
  "House of Cards",
  "Turret",
  "Sly Carrot",
  "Egg Top",
  "Stardust mask",
  "LBM Mask",
  "Burg Invasion",
  "Citadel Tophat",
  "Tentacus",
  "Evacuated",
  "Freighted",
  "Industrial",
  "Kanjo",
  "Tiki",
  "Sawblade",
  "Oasis Guardian",
  "Sandstorm Supply",
  "Under-Cover",
  "On Site",
  "Sky Spinner",
  "Little Truck",
  "Palm Hair",
  "Sub Gondola",
  "Temple-top",
  "Rooster",
  "Acidic Bane",
  "Beaked",
  "Locked Up",
  "Location Pin",
  "Juicer",
  "Templar",
  "Annoying Captcha",
  "JDM",
  "Kings Guard",
  "Krunker at Home",
  "Krum Pong",
  "Shelly",
  "Operator",
  "Neuro Link",
  "Puppeteer",
  "Reindeer Antlers",
  "Clockwork",
  "Aussie",
  "W-Tron",
  "F for Respect",
  "Love at first sight",
  "Ace",
  "Snappy",
  "Oversized Headset",
  "Missing Piece",
  "Swagger",
  "Bolted",
  "Run Away!",
  "Trashman",
  "Claws",
  "Lord Panda",
  "Unicorn",
  "Clown",
  "Rainbow Afro",
  "Starry Visitors",
  "Emoji Beanie",
  "Hypno",
  "Cirangle",
  "Zombie Head",
  "Crayator Bandana",
  "Scuffed Bandana",
  "Loserfruit Bandana",
  "Zed Bandana",
  "Quacky Bandana",
  "Ok Dude",
  "Rave Glasses",
  "Shlem",
  "Headshot",
  "Green Alien",
  "Purple Alien",
  "Bone",
  "Candy Cane",
  "Carrot",
  "Teeth",
  "Gunpowder",
  "Meat",
  "Spark Plug",
  "Message in a Bottle",
  "Nocturnal",
  "Grill Time",
  "Acid Bane",
  "Plasma Bones",
  "Watercooled",
  "Guardian of Atlantis",
  "Jackpot!",
  "Dimensional Fracture",
  "Vassal",
  "Big Meat",
  "Master Key",
  "Pearl",
  "Shermy Pillow",
  "Copeghetti",
  "Shark Fin",
  "Hooper",
  "Starlight Jet",
  "Penciler",
  "Padded",
  "Gift",
  "Daisy",
  "Pink Daisy",
  "Blue Daisy",
  "Acceptance Letters",
  "Explosive",
  "Angelic Wings",
  "Workers Vest",
  "Doom Tentacles",
  "Fan",
  "Fermenter",
  "Krum Dispenser",
  "Undead Body",
  "Pie",
  "Maid's Apron",
  "Cursed",
  "Backstabber",
  "Vender",
  "Egg Shelled",
  "Argentina Trikot",
  "Australia Trikot",
  "England Trikot",
  "Spain Trikot",
  "France Trikot",
  "Germany Trikot",
  "Ghana Trikot",
  "Iran Trikot",
  "Japan Trikot",
  "Korea Republic Trikot",
  "Mexico Trikot",
  "Morocco Trikot",
  "Belgium Trikot",
  "Holland Trikot",
  "Poland Trikot",
  "Portugal Trikot",
  "Qatar Trikot",
  "Saudi Arabia Trikot",
  "Senegal Trikot",
  "Serbia Trikot",
  "Switzerland Trikot",
  "Tunisia Trikot",
  "Uruguay Trikot",
  "Brasil Trikot",
  "USA Trikot",
  "Wales Trikot",
  "Cameroon Trikot",
  "Canada Trikot",
  "Costa Rica Trikot",
  "Croatia Trikot",
  "Denmark Trikot",
  "Ecuador Trikot",
  "Operator Vest",
  "Samurai Blades",
  "Phase Blades",
  "Cyburai Blades",
  "Unicorn Backpack",
  "Actual Nr.1",
  "Promise rings",
  "Scaled Wings",
  "Ladybug",
  "Armstrong",
  "Roman",
  "Stealthy",
  "Scifi Panel",
  "Payphone",
  "Red Ribbon",
  "Carockets",
  "Carrot Blades",
  "Chick N' Basket",
  "Blood Harvest",
  "KrunkBoy",
  "Lantern",
  "Hellbound",
  "Nuke",
  "Panda Body",
  "Bear Body",
  "Viking",
  "Kruncade",
  "Fully Loaded",
  "Local Bakery",
  "Mechladon",
  "Up",
  "CyberLex",
  "Toby Backpack",
  "Swag Bag XL",
  "Dark Armor",
  "Samurai Armor",
  "Cyburai Armor",
  "Fender",
  "Gibson",
  "Disco Wings",
  "Crimson Fairy",
  "Fairy",
  "Sprout",
  "Sweet N Sour",
  "MetalPops",
  "Jumbo Jet 1",
  "Jumbo Jet 2",
  "Quad",
  "Baby Panda",
  "Altered Buddy",
  "Dont Shoot",
  "Krunk League",
  "Robbery",
  "Santa's Sack",
  "Santa Belt",
  "Swag Bag",
  "Apex Predator",
  "Witch's Brew",
  "Bunny Tail",
  "Operator Belt",
  "Flamingo floatie",
  "Lizard Tail",
  "Tiger Tail",
  "Raindeer Tail",
  "Carroperator Belt",
  "Good'ol'Belt",
  "Infected String",
  "Scales",
  "Trophy",
  "Chained",
  "Happy",
  "Flushed",
  "Fish-Faced",
  "Gremlin",
  "Horrified",
  "Senior",
  "Chief",
  "Scar",
  "Glowup",
  "Suspicious",
  "Sockets",
  "Angwy",
  "Agony",
  "Fly Catcher",
  "Tea Time",
  "Bad Day",
  "Silenced",
  "AHHHHHHH",
  "Kitty",
  "Sea Sick",
  "Heartbreak",
  "Braces",
  "Serenity",
  "Huh",
  "Dazed",
  "Pleased",
  "Deprived",
  "Cheeky",
  "Shocker",
  "Gah",
  "Caveman",
  "Chipped",
  "Kids",
  "Unlucky",
  "Mistress Krunker",
  "Waaah",
  "Tipsy",
  "Drowzy",
  "BRAINZ",
  "Yikes",
  "Turkey Time",
  "Krunksgiving",
  "Gluton",
  "Host",
  "Connection Error",
  "Blinker",
  "Yikers",
  "Maniac",
  "Shades",
  "Jolly Saint",
  "Nightmares",
  "Empty",
  "Panda",
  "Muted",
  "A Little Sad",
  "Double Chinner",
  "Dizzy",
  "Monkey",
  "Happy Gramps",
  "Skully",
  "Disappointment",
  "Kawaii",
  "Orc",
  "Rage",
  "CatBoy",
  "Charlot",
  "Stache",
  "Krunkhead",
  "Martian",
  "Kalm",
  "Tiger Clawed",
  "Chiseled",
  "Happy Alien",
  "Saw A Bug",
  "Cat Owner",
  "Uncle Nuke",
  "Human",
  "Mole",
  "Chompers",
  "Punker",
  "Oopsie",
  "Bugged",
  "Enjoyer",
  "Very Serious",
  "Triangular",
  "Simp",
  "Judgemental",
  "Mouse Head",
  "Sly",
  "Emo",
  "KRovo",
  "Purple Haze",
  "Toad Head",
  "Gloom",
  "Nerd",
  "Lifter",
  "Accident",
  "Nose of Anger",
  "Bro",
  "Doh",
  "Wooden Brainz",
  "Iron Monkey",
  "Heart Break",
  "Space Ripper",
  "Bucky",
  "Ded",
  "Snow bro",
  "Baller",
  "Tunnel Vision",
  "Squished",
  "Red Eyed",
  "Double Barrelled",
  "Space Vision",
  "SlimeTime",
  "Little Friend",
  "Death Bot",
  "Bunny",
  "Reader",
  "Pay Day",
  "Bad Breath",
  "Robo",
  "Galaxy Eye",
  "Stitched",
  "Oops Gum",
  "Blind Shot",
  "Future Soldier",
  "Suprise Headshot",
  "Puppy",
  "Melted",
  "Too much TV",
  "Perfect Vision",
  "WiseMan",
  "Swamped",
  "Eyeception",
  "Old Timer",
  "Follow Me",
  "First Round",
  "Smirk",
  "Uncle Bro",
  "General Zlar",
  "Chill Brah",
  "Cat Fished",
  "Brow Day",
  "Cheeky Sus",
  "First Kiss",
  "Moderator",
  "KPD OverTime",
  "Popular",
  "Lil Friend",
  "Huh?",
  "Bunkie",
  "Serpentine King",
  "Peter the Cranky",
  "Craze the Hanger",
  "Bunkie 2",
  "Cyborg Crane",
  "Mad Senei",
  "Clueless",
  "Crusty",
  "Bored",
  "Unhinged",
  "Bootleg",
  "Primitive Steve",
  "Youngin",
  "All Seeing Eyes",
  "Retro Kitty",
  "Sure",
  "Happy Kitty",
  "Vexed",
  "Definitely friendly",
  "Long Nights",
  "Big Forehead",
  "Thomas",
  "Trip Wire",
  "Whimper",
  "Bitey",
  "Old Hoot",
  "Scheming",
  "Musky",
  "Happy'thulu",
  "Boredom",
  "Stardust smirk",
  "Super Hero",
  "Chewie",
  "Morb",
  "Super Krunked",
  "Vengeful Hero",
  "Professor spence",
  "Wrencher",
  "Squished",
  "Cheesy grin",
  "Goofy ah",
  "Pushing it out",
  "Permanent Brainfreeze",
  "Black hole",
  "Lumberjack",
  "Dont touch my crops",
  "Ello",
  "Shy-guy",
  "Sleep &lt; Caffeine",
  "Uncomfortable",
  "Geeky",
  "Seriously?",
  "Overheating",
  "Speechless",
  "Babyboy",
  "Greedy",
  "Hazy",
  "Impassioned",
  "Washed",
  "Drooler",
  "Rockmonster",
  "Licker",
  "Pure Darkness",
  "Mr. Lover",
  "Mr. Small",
  "Depressio",
  "Right in the feels",
  "Styler",
  "It Hurts",
  "Grumpy Dad",
  "Milker",
  "Sleeper",
  "Krunkinator",
  "All Seeing Eye",
  "Comical Nerd",
  "Sweety",
  "Scardy Pants",
  "Forehead Licker",
  "6x Vision",
  "Resident Sleeper Mode",
  "Crosseyed",
  "Outlaw",
  "Space Patrol",
  "Ayo?",
  "Ouchie",
  "Casandra Love",
  "Terrifying",
  "Friendly Foe",
  "Wormie",
  "Don't Pick Me",
  "No Dental Plan",
  "Mouthfull",
  "Sarah",
  "Oh Yeah?",
  "Spoof",
  "Big Dreamer",
  "Dumm",
  "Determined",
  "Toothy",
  "Karen",
  "Too old for this",
  "Wise Man",
  "Over Thinker",
  "Shocker",
  "Peppermint Pal",
  "The Nutcracker",
  "Fused",
  "Lover Boy",
  "Oopsy",
  "Lover Girl",
  "Egg Hunt",
  "Bun",
  "Tulip",
  "Crooked",
  "Cyber Chad",
  "Among Andy",
  "Sniffler",
  "Blush",
  "Crazy Stache",
  "Stepped in Doo Doo",
  "Buttons",
  "Empty Inventory",
  "Flame Horns",
  "Ghosted",
  "Feelin' Catty",
  "UwU",
  "Torn Flesh",
  "Lil'Bro",
  "Uncle Bruiser",
  "Say Cheese",
  "Dad Joe",
  "Attacked by Onions",
  "Arrogant",
  "Royal Angel",
  "Royal Leader",
  "Faceless",
  "Patchy",
  "Rusty",
  "Red Beard",
  "Grumpy Patchy",
  "Angry Patchy",
  "Puppeteer",
  "Button-face",
  "Soulless",
  "Pierre",
  "Sly",
  "Bewildered",
  "Flirtatious",
  "Redneck",
  "Four Eyes",
  "Spooky",
  "Sniffer",
  "Brows",
  "Forced Smile",
  "Gummy",
  "Candy Teeth",
  "Gypsy",
  "Grinner",
  "Snotty",
  "CaptainKrunker",
  "CaveKrunk",
  "Krunkenstein",
  "Zombified",
  "Tricker",
  "Star Shoes",
  "Operator Boots",
  "Raindeer Hoof",
  "Raptor",
  "Slipper",
  "Panda Paws",
  "Krocs",
  "Damascus",
  "Prism",
  "KRPD Recruit Blade",
  "Valkyrie",
  "Magic Wand",
  "Star Wand",
  "Timeless",
  "Dragonclaw",
  "Furball",
  "Suede Blade",
  "Crimson Tiger",
  "Vaporblade",
  "Verdant",
  "Juice Box",
  "Bamboo",
  "Kohaku",
  "Case Harden",
  "Cyb Punk",
  "Blue",
  "Future Slicer",
  "Flamyngo",
  "Red Blade",
  "Acid Breath",
  "Wired",
  "Kings",
  "Sunset",
  "Cuircuitor",
  "Sorable V",
  "Wasteland",
  "101 Skullbreaker",
  "Lederhose",
  "Heat Stroke",
  "Clockwork",
  "Spec Ops",
  "Toxic Nitro",
  "Royality",
  "Firestorm",
  "Sense",
  "Unistorm",
  "Void X",
  "Eira",
  "Neigh",
  "Combined",
  "The Star",
  "Kortex",
  "Arae Atlas",
  "ThiccChemist",
  "Upset",
  "Vassago",
  "Sunshine",
  "Heart Cycle",
  "Whippii",
  "Kanj",
  "intergalactic takeaway",
  "3-E",
  "Bullets",
  "Red Panda Playground",
  "Omen",
  "Testing",
  "Metro",
  "Death Goat",
  "Kyanite",
  "Dismay",
  "Telescope",
  "Neonic",
  "Krunker'77",
  "OPTILINE",
  "Rudolph",
  "Unwrapped",
  "Constellation",
  "Elemental Trio",
  "Thunderclap",
  "Mechanically Organic",
  "MPIRE",
  "Black Flag",
  "Corsair",
  "Swixie",
  "Hand Cannon",
  "kdc",
  "Lava Bolt",
  "Rien",
  "Sandstorm",
  "Whippington",
  "#4thekids",
  "Wormhole",
  "Krnk",
  "Ruby Sight",
  "Alaric Void",
  "Policia!",
  "Wiring",
  "KSG",
  "Space Hunter",
  "Proto-Blaster",
  "HawtRod",
  "GOG*",
  "Boop-Kroonks",
  "Prestige",
  "Outpost",
  "Facility_41",
  "Tachyon",
  "Military Produced",
  "Kolt Rifle",
  "ZNIP3R",
  "Golden Turkey",
  "Starlight Sight",
  "Noël",
  "AWP!",
  "Z-2810",
  "Reine",
  "Lunar Temple",
  "Inix",
  "pSYch0 !",
  "cheri",
  "berri",
  "swit",
  "Moon Dragon",
  "Viper",
  "Masterpiece",
  "Repeating",
  "Array",
  "kiukiu",
  "N.O.I.R",
  "Anarchy",
  "Haste",
  "Desert Strike",
  "Leine",
  "Lucky Clover",
  "Charged Pulse",
  "Lime Coated",
  "Theta",
  "nV Dragon",
  "Spook",
  "Kenzo",
  "Neon Spill",
  "Tazor",
  "Archive",
  "Boom",
  "CHAMPIONS",
  "Jef",
  "Keys",
  "Allsmiles",
  "Really",
  "Corrosive",
  "Comic Tracker",
  "Milspec-MCD",
  "Cyclonic-RGB",
  "Corpo",
  "SN0W",
  "Plasma Grime",
  "Graffiti",
  "Krystal",
  "Thunder God",
  "Dynamite",
  "Luminescence",
  "SunBurst Swirl",
  "Rockstar",
  "SMILEZ",
  "Chameleon",
  "Vizual",
  "Lightning Vein",
  "Kyanite",
  "Retrocade 2.0",
  "Sahara Ops",
  "Dot Product",
  "Barabasz",
  "Xanaved",
  "UZI.daw",
  "Jaw O Death",
  "energy",
  "PowerX",
  "Bubblegun",
  "Space Launcher",
  "Purple Tech",
  "EZ Frag",
  "Alpha",
  "PicKk",
  "Boaba",
  "Horus Legacy",
  "Pixel Fade",
  "Orange Ship",
  "Fervor",
  "Laboratorix",
  "Ginova",
  "Pocket Sniper",
  "Ugly Sweater",
  "Grantz",
  "Manolo",
  "Interconnected",
  "Warhawk",
  "Luminescent Drip",
  "Horus",
  "Project-Evac",
  "T.5-LAUNCH",
  "Houres",
  "ThiccChemist",
  "Zircon",
  "Ye",
  "Quacker",
  "Wyvern",
  "Sidious",
  "Ultima",
  "Xantium-50",
  "DUTKG",
  "Digiaudio",
  "Sports",
  "Fleece",
  "Speed Demon",
  "Dmg",
  "Immortal.50",
  "Just Deagling",
  "Igurr",
  "Splasher",
  "Krumshot",
  "Holoz",
  "JET BOY",
  "Celestrofeo",
  "Tigris",
  "Rawrinator",
  "FFastforward",
  "RCER2022",
  "Records",
  "Militoy",
  "Synthetic",
  "RNITBK",
  "SCiTHE",
  "Laser Radiation",
  "FIUUUMBA",
  "Smiley-Blaster",
  "Prototype-14",
  "K9X",
  "X-Commando",
  "Royale Bow",
  "Neon Hunter",
  "Sabre",
  "Fadeland Tactical",
  "Stripes-3",
  "Violet Ravager",
  "Morse-3",
  "Jungle Stalker",
  "Kaleido",
  "Overheated",
  "Lost in Space",
  "Sparta",
  "T.A.N 9",
  "Alchemical X-Commando",
  "Sunset Predator",
  "Cupidon",
  "Futurai",
  "Marblelous",
  "Cross Reborn",
  "GrapeShot ",
  "Firefighter",
  "Data Corruptor",
  "Hunter",
  "Space Ranger",
  "Party Animal",
  "Policijia",
  "Crusader",
  "Rye",
  "Midnight Phoenix",
  "Shortcake",
  "Kortal",
  "VR-4",
  "Admiral",
  "Spike",
  "Dragon Koi",
  "World Eater",
  "Black Cats",
  "Dezein",
  "Scorpio",
  "Thorny",
  "Irresponsible",
  "Kyanite",
  "NutKRacker",
  "Arcadist",
  "Chemical Zebra",
  "ColorWave",
  "Zerulaw",
  "Overkill",
  "Elia",
  "Pipeline",
  "WSugarCherry",
  "ABOYISAGUN",
  "Check",
  "Josu",
  "K&amp;R",
  "TigerTech",
  "Celebrations",
  "Boneclaw",
  "Hero's advice",
  "FS SPRHornet",
  "SK-577",
  "FMS",
  "bLIMEy",
  "Pinkception",
  "BaseDef-2",
  "Disco-Krunk",
  "Spook",
  "Kenzo",
  "Marked",
  "Gold Tipped",
  "World of Light",
  "Spiritful",
  "Lxd",
  "Peruvia",
  "Caged",
  "Turbocharged",
  "Solar Shot",
  "Kittco",
  "Pistulin",
  "Koiled",
  "FREEEEEEEE",
  "Boomba",
  "Canned trip",
  "DnPAINT",
  "Dragon's Blossom",
  "ST3-Punk",
  "Killitt",
  "EDGERUNNER",
  "Up",
  "R3TRO",
  "Slayer",
  "No Mutiny",
  "Scarlet Shot",
  "Kiiro",
  "Slayed",
  "Christmas Cannon",
  "Noble Hitman",
  "Modular",
  "Skullwood",
  "Heartbreak",
  "Speedy",
  "Tribe",
  "Heat Spot",
  "Motion",
  "Shed",
  "Hol",
  "Auto Polymer",
  "Security Breach",
  "Fortuni",
  "Red Call",
  "Snow Candy",
  "KIGA",
  "Companion",
  "Shaman's Dream",
  "Doppler",
  "Termination",
  "SRT6 Fade",
  "Desert Ace",
  "Stripez",
  "Voyager-73",
  "Rutilus",
  "Infer",
  "Absolute",
  "8",
  "Raqar",
  "Cyan Shot",
  "G4-18",
  "L&lt;3VE",
  "Walkit",
  "Mecha-18",
  "Apis",
  "Yahmean",
  "Fono",
  "Contrucction",
  "KrunkieBoy",
  "Tombskull",
  "Sweet Shot",
  "Big Krunk",
  "Pixel Tiger",
  "Synopsis",
  "Vandalism",
  "Block-18",
  "Krunkys",
  "2k",
  "Wedding",
  "Sn0wflake",
  "Nacia",
  "Model CIMM",
  "PowerUnit",
  "Jet-XZ2",
  "Maquina",
  "ProTun",
  "MockSIDZ",
  "Pirzo",
  "Looper",
  "Vectronica",
  "Bob.",
  "Submergence",
  "HZR-D",
  "local file",
  "The Queen of Hearts",
  "Cyber Blocked",
  "KP0LicE",
  "Hokusho",
  "Syrusek-VX",
  "Starlord",
  "Nikorienka",
  "Division X",
  "Khazzar",
  "Ultra Moist",
  "Tiger Blast",
  "Emerald King",
  "Cherry Blossom",
  "Yellothax",
  "Roxxe",
  "Speedster-13",
  "Scribbler",
  "Crimson",
  "Damascus",
  "Shinto",
  "Lantern",
  "Farmland",
  "Horisun",
  "Wims",
  "Amaterasu",
  "Eurasian",
  "Fantasy",
  "Krunkodore",
  "Creature",
  "Disco",
  "Toxic Nitro",
  "Atheris",
  "Akhenaten",
  "Abducted",
  "Hannya",
  "Drakon",
  "Cactus Jack",
  "Pestilence",
  "Death Rattle",
  "Soda-Licious",
  "Teknic",
  "Dungeon Crawl",
  "Hydrogen",
  "Hokage",
  "Doragons Influence",
  "Wrong Number",
  "Lava Rifle",
  "Kyanite",
  "Shooting Star",
  "Dimension",
  "AL-405",
  "Nightmare Fuel",
  "CPU",
  "Minimal",
  "Burnt Memoir",
  "Golden Emissary",
  "Town Defender",
  "Turbo Boost",
  "Exo-Ship",
  "CIMOTAKOV",
  "Black Pearl",
  "Blue Beard",
  "Redzone",
  "Schloss",
  "Town Blueprint",
  "Voltage",
  "Stellar",
  "Elimination",
  "ST4LK3R",
  "Drake's Wrath",
  "Mushroomclouds",
  "Fallout",
  "Orca",
  "DNMOB",
  "Beep-Boop",
  "Spirit",
  "Shii",
  "News",
  "KKio",
  "GRID!",
  "Suetic",
  "Bushido's Honor",
  "Dia De Muertos",
  "Starlight Voyage",
  "Void's Devour",
  "Shiner*",
  "REALITY",
  "Steamcraft",
  "Powertrip",
  "Doom's Day",
  "Mecha",
  "Luna Dragon",
  "Winter Predator",
  "Imouto!",
  "Mecha Nemesis",
  "Flipside",
  "AKRCER22",
  "lighter than Life",
  "darker than Death",
  "Zino Lips",
  "for.the.uninitiated.",
  "STARKILLER",
  "Lux-0-200",
  "LIT A$AP",
  "Texan",
  "Saviour",
  "Lucky Clover",
  "ShiftX",
  "Motorsport",
  "AK Gold Rush",
  "Phantasma",
  "Zebrik",
  "Red Rod",
  "Vultaric",
  "Invader",
  "SPEEDER 06",
  "TurboU",
  "is-me",
  "y-me",
  "th-me",
  "LBM",
  "Splash",
  "Boated",
  "Lowercase p",
  "Pink Punk",
  "Truck",
  "Zapped",
  "Space Case 73",
  "The Explorer",
  "Lifeline-KRNK",
  "Mostang",
  "kommandant",
  "kommando",
  "Silent",
  "Gold CZ",
  "Solly",
  "sCiFi",
  "wod",
  "AMYGDALA",
  "Gas Leak",
  "Crow Elite",
  "Charge Byte",
  "cracked",
  "World War",
  "Ra's Paradise",
  "Blaster-X",
  "Flight",
  "Kastro",
  "TnT",
  "GV212",
  "Azetic",
  "Ordinary",
  "Silenced Stingray",
  "Hologram",
  "UNSC-INC",
  "Holo",
  "Xorhu",
  "Tigress Dynasty",
  "Tiger's Might",
  "Hell Tooth",
  "Prismo SID",
  "Avenger-X",
  "Defender-X",
  "USP 2022",
  "Pur",
  "SmileSturr",
  "Krunkdam",
  "115",
  "Regal",
  "Cracked Ruby",
  "Andromeda",
  "Liberty",
  "Cimota",
  "Fractal",
  "Trip",
  "T3CH",
  "Cassette",
  "Festive",
  "Traveller",
  "Abraxas",
  "SMG Spitfire",
  "Doodle",
  "Carcinogen",
  "Spinner",
  "Occult",
  "Merlin",
  "TV Strike",
  "Taurine",
  "Amethyst",
  "Northern",
  "Agent",
  "Lester",
  "Bloodlust",
  "Kanashii",
  "CIRO",
  "Iara",
  "Jakku",
  "Siktis",
  "Headhunter Alpha",
  "Ragnarok",
  "BoomBox",
  "Shogunner",
  "Project Firefly",
  "AYSY",
  "Kyanite",
  "SubStar",
  "BRAINWASH",
  "Lava SMG",
  "Controlled",
  "Raptor",
  "Krunklair",
  "Golden Fish",
  "14O",
  "Yucatan",
  "Hakka",
  "Sherbet",
  "Neon Burst",
  "1980",
  "War Trophy",
  "Sunspot",
  "Ultra CyberNetiks",
  "Cloud Nine",
  "CONSP11RE",
  "Royal Palace",
  "Angler",
  "Ruby",
  "Chorose",
  "Eternal Rest",
  "Proto",
  "Mecha Citrus",
  "Mint",
  "Limitless",
  "Blorange",
  "AERO",
  "Extraterrestrial",
  "Starry Friends",
  "ToXiC RiG",
  "Lostndfound",
  "Symphogear",
  "CMYK",
  "Interstellar",
  "Polarized",
  "CyberArms",
  "TriNitroToluene",
  "Thermal",
  "Loop",
  "Limech",
  "Spectar",
  "Bawl",
  "Cyber Grunge",
  "Static Smile",
  "Mech Division 30",
  "smg",
  "Decryption",
  "SM.GG",
  "Data Stream 7",
  "Moenza-067",
  "Rev 2058",
  "Kotal",
  "Acid Bark",
  "Lonely",
  "Flower Power",
  "Living Dead",
  "Little Bite",
  "El Matador",
  "Kyanite",
  "Toucan",
  "Hades Blaze",
  "Ginger Cannon",
  "Yellow Flash",
  "Phantom_Kille",
  "Vision",
  "Devil's Torment",
  "Crocodile",
  "Factory Finish",
  "Toxic Splash",
  "Ahoy!!",
  "Mecha Zombie",
  "Dystopian Rebel",
  "Revvie",
  "Kuzer",
  "Taltast",
  "L2021",
  "Turee",
  "Vlad's Cannon",
  "Ruins",
  "Kitegon",
  "Virus",
  "Livid",
  "Venger",
  "Factory Issued",
  "Vickeran",
  "Captain Cold",
  "Venomous",
  "Lava Revolver",
  "2 Hot 2 Handle",
  "Necro Scream",
  "Phaser",
  "NEO",
  "Kolivier",
  "Flare",
  "Newage",
  "Lost in time",
  "Mayumi-7",
  "Porcelain",
  "Party Reptilia",
  "Recrafted",
  "Recreated",
  "Molten Ionized",
  "PH-0-EN-X",
  "Targeted",
  "Blue Amethyst",
  "Captain Star-Z",
  "Euphoric",
  "Cutout",
  "BOO!",
  "Bluezea",
  "Right stand",
  "Merry Kill-mas",
  "Ginger Python",
  "Lucky Clover",
  "Carrot Rev",
  "6am",
  "6pm",
  "Lust",
  "OVRC",
  "Razor Madness",
  "Overheated",
  "Royal",
  "Outlaw",
  "Chrome",
  "S&amp;Y",
  "Trix",
  "Hades",
  "Excalibur",
  "Zeus",
  "Zap",
  "Midas",
  "Anatomis",
  "Shot Element",
  "Anodized",
  "Roadkill",
  "Sarin",
  "Nitrox",
  "Imperial",
  "Foria",
  "Death Rise",
  "Keanu",
  "Spook Town",
  "DragonBorn",
  "Blossom Revenge",
  "One Off",
  "CyberBuddy",
  "Kyanite",
  "Gift Wrapped",
  "Korder",
  "ZPVC",
  "Popstar 77",
  "gunz",
  "Commmander",
  "Mimir",
  "Ghost Town",
  "Peacekeeper",
  "Pap1024",
  "Krunkieboy 3.0",
  "Servershot",
  "NUKED",
  "Banco",
  "Sequel",
  "Sankakkei",
  "Boomie",
  "Krunkerheads",
  "2rb Seq2",
  "Dolersn",
  "Refferi",
  "Atomic Shot",
  "Home Defense",
  "Mecha Figuration",
  "Glace",
  "Cyber Blossom",
  "T1GA",
  "P1NK!",
  "Chr!stine",
  "Somba",
  "Sumba",
  "Cosmic",
  "The Vibe",
  "Puma-S",
  "Bloodline",
  "Urban Ops",
  "Fire Place",
  "Snowman Maneater",
  "Lucky Clover",
  "Krunk Air",
  "Sahara Strike",
  "Cupid Shot",
  "Vali",
  "Duchess",
  "Teknoka",
  "Sunset Raven",
  "Toxix",
  "Incognito",
  "Scalar",
  "Monatomic",
  "Egg Catcher",
  "Eggcellent",
  "Red Supersport",
  "Pink Supersport",
  "Ethereal",
  "Spectate",
  "Hydrofluric",
  "Midnight",
  "Blazed",
  "Tri-Tech",
  "Toxic Rider",
  "FSS Archdaemon",
  "Society",
  "Loch Ness Monster",
  "Kyanite",
  "Werner",
  "Sakura",
  "Sunstorm-60",
  "Viscount",
  "Conde",
  "Jonke",
  "AstroLMG",
  "Deep Bass",
  "Octopus Revenge",
  "Checkmate",
  "Heaven's Trophy",
  "Lava LMG",
  "Imperial Jade",
  "Imperial Garnet",
  "Chartreuse",
  "Xorffiti",
  "Zebrik",
  "Neoran",
  "Fire Breath",
  "Sonar",
  "Icevein",
  "Demonvein",
  "Magnis",
  "Zombie Eliminator",
  "Neocore Chameleon",
  "Cobblestone",
  "Battle Tested",
  "Site",
  "KSFSemi-Rev3",
  "Kruncher",
  "WYWH",
  "Dragmota",
  "Warp",
  "Stripe",
  "Shift MK2",
  "Golden",
  "Strawberry",
  "Metalfold-1",
  "Halloween Night",
  "Titanium ET7",
  "Disruption Break",
  "Spectral Tiger",
  "All-Man",
  "Monochrome",
  "AR-comp",
  "Odyssey",
  "Yelm08",
  "Shift",
  "Funky Town",
  "Secrets Of Nile",
  "Dessolate",
  "Stanik",
  "Eaglx",
  "Aesthetica",
  "MOS",
  "Fireball",
  "Noble Guard",
  "Institute",
  "Streamer",
  "Avalan",
  "Disruptor",
  "Phusion",
  "Man vs God",
  "Wildlife",
  "Wharf",
  "ZE-14",
  "Ripjaws",
  "Wind",
  "Costume Party",
  "Kyanite",
  "Crystal",
  "Frozen",
  "NUKE CRACKER",
  "Lava Rocket",
  "Coffin",
  "Kyanite",
];

export const epic_labels = [
  "Color Your World",
  "Streak",
  "Into the Void",
  "Orange Tiger",
  "White Tiger",
  "Teal Tiger",
  "Blue Tiger",
  "Green Tiger",
  "Hex Matrix",
  "Kamouflage",
  "Cherry Blossom",
  "Atomize",
  "Top Hat",
  "Ducky",
  "Wizard",
  "Brown Beard",
  "Blonde Beard",
  "Twitched",
  "Paraseye",
  "Braindead",
  "Krunk Headset",
  "Cherry Headset",
  "Goblin King",
  "Lincoln",
  "Rice Hat",
  "Blonde",
  "Ranga",
  "Elvis",
  "Brunet",
  "Fancy",
  "Beaver",
  "Lucky",
  "Black Cloak",
  "White Cloak",
  "Stupid",
  "Pope",
  "Uranium",
  "Magic",
  "Black Bucket",
  "White Bucket",
  "Green Present",
  "Red Present",
  "Red Mask",
  "Green Mask",
  "Blue Mask",
  "Pink Mask",
  "Red Eye",
  "Blue Eye",
  "Mad",
  "Notification",
  "Cleaver Head",
  "Cat Ears",
  "Winter Hood",
  "Kitty Headphones",
  "Flushed Heart",
  "Snowman",
  "Kitsune",
  "Swearing",
  "Check Trades!",
  "MooMoo",
  "William Tell",
  "Boxxi",
  "Monke",
  "Cupcake",
  "Abused laptop",
  "Love Bands",
  "Diamond Helmet",
  "Pink Pacifier",
  "Blue Pacifier",
  "Nuggi",
  "Black Balaclava",
  "Peary",
  "Rainbow beluga",
  "Turd",
  "Jolly Wingman",
  "Rubic",
  "Rest Stop",
  "Impacted",
  "Freshen up",
  "Distinguished Bunny",
  "Soldier 159",
  "Soldier 160",
  "Trunk",
  "Balanced Diet",
  "Mush Top",
  "Baked",
  "Cant CD's eyes",
  "You got mailed",
  "Downforce",
  "Sprout",
  "BIG L",
  "Free DLC",
  "Sad Default Cube",
  "Failed Experiment",
  "Medic Helmet",
  "Profile",
  "Files",
  "Whats this ?",
  "Old Man",
  "Tasty",
  "Cut here",
  "Anger",
  "Scribble",
  "Bricked",
  "Dr.Jon",
  "Butter",
  "Status",
  "Custom Keyboard",
  "Dutch",
  "Special Goggles",
  "Mr. Rabbiton",
  "Madman",
  "Grizz Lee",
  "Simba",
  "Captain Walrus",
  "Monke",
  "Sweet Rays",
  "Snowman",
  "Misty",
  "Facemask",
  "Carrot Top",
  "Mr Chick",
  "Bunny",
  "Hotdogger",
  "Sergeant",
  "Witch",
  "Bear Mask",
  "Panda Mask",
  "Big Apple",
  "Banananana",
  "Coolman",
  "Wood",
  "Tin Can",
  "Cloth",
  "Wrapping Paper",
  "Wires",
  "Season 6 Elite Ticket",
  "Season 7 Elite Ticket",
  "Bass Guitar",
  "Croissant",
  "Candy Caner",
  "Games for Love",
  "I Love Krum",
  "Spouse Splatter",
  "Climber",
  "Boarded",
  "VIP Peanut",
  "Lipstick",
  "Painter",
  "Red Tie",
  "Keyboard",
  "Foosballer",
  "Jet Pack",
  "Mix Tape",
  "Stop Sign",
  "Krunkie Magnet",
  "Wheelie Bin",
  "Bulletproof Vest",
  "Back to skool",
  "Muncher",
  "Fire Fighter",
  "Fabulous Sailor",
  "Medal",
  "Medal I",
  "Book Worm",
  "Referee",
  "Toothy",
  "Zipper",
  "Outtage",
  "Bunny Suspenders",
  "Butterfly",
  "Pot'O'Gold",
  "Serious Bling",
  "Pouch",
  "Fully Caged",
  "Raindeer Brace",
  "Inspected",
  "A lil'Fishy",
  "Overachiever",
  "Krunker.io",
  "Keepers key",
  "Egg Basket",
  "Charged Up",
  "Skeleton Grip",
  "Spider Grip",
  "Sir HotDog",
  "Roman Shield",
  "Timeless Shield",
  "TTV Vest",
  "Butcher",
  "Scales",
  "Pauldrons",
  "Milk Chocolate",
  "White Chocolate",
  "Dark Chocolate",
  "Tehch Deck",
  "Slidehop 101",
  "Swipe Left",
  "Krunk to the Future",
  "Lil Buddy",
  "Skelly",
  "Endoskeleton-5",
  "Mech Frame",
  "Trophy",
  "Totally Normal",
  "Krunk Landing",
  "2004 Belt",
  "Goop",
  "Tessalate",
  "Poly Blush",
  "Marbled .50",
  "Turbo",
  "Emboss",
  "Spineless",
  "Gold Plated",
  "Shattered",
  "Lunar Nitro",
  "Retribution",
  "Crator",
  "Violet",
  "Savaged",
  "AWM Federation",
  "Fairy",
  "Nozomu",
  "Candy",
  "Choc",
  "Pastel",
  "Scoped Elite",
  "Yurei",
  "Vaporride",
  "Alligator",
  "Jungle",
  "Stickerbomb",
  "Barbed Rifle",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Reticle Blaze",
  "Olympus Rifle",
  "Cranium",
  "Seishin",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Tsunami",
  "Hemp",
  "Kunzite",
  "Tiger Bolt",
  "Ho-Ho",
  "Candy Cane",
  "Zebra Bolt",
  "Mistletoe",
  "Festivity",
  "Sky Bolt",
  "O RLY?",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "AWP Supersport",
  "Book of Shadows",
  "Year of the Tiger",
  "Fuzzy Finale",
  "Dipped Blackout",
  "HBA",
  "Clouded",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "3Lite Merf",
  "Raid",
  "Polydrive",
  "Cherry Blossom",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Fabrica",
  "Azazel",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Galaxy",
  "Paint Spill",
  "Dual Seafarer",
  "808s",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Tiger Warfare",
  "Dipped Blackout",
  "Sticker bomb",
  "Clouded",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Kitta",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Ocean",
  "Cranium",
  "Orah",
  "Krunk Wet-Cannon",
  "Stormy",
  "Ducky",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Hemp",
  "Kunzite",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Arctic Drake",
  "Sweet Delight",
  "PowderBlue",
  "Wrapped up Deagle",
  "Golden Moon",
  "Relic Hunter",
  "Abyxxel",
  "Optimus-0",
  "Elite Mod Xbow",
  "Fish Warfare",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Isotope Mk2",
  "Cranium",
  "G2 Barb",
  "Nebulous",
  "Digital Supremacy",
  "Frosting",
  "Trick or Treat",
  "Crusade",
  "Emoji",
  "Triple Olympus",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Kunzite",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Confusions",
  "Reticle Burst",
  "G2 Tigris",
  "Trashy",
  "Zebra Burst",
  "EMR-SPH",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Skyfarer",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Commando Fade",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Veteran",
  "linekill",
  "cielo",
  "Clouded",
  "Wrapped up Famas",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Raid",
  "Cascade",
  "War Torn",
  "Fabrica",
  "Zebrik",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Paint Spill",
  "Slime Spill",
  "Fireburst",
  "Moldavite",
  "Scribble",
  "Snapple",
  "Released Kraken",
  "Freshly Picked",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Sticker bomb",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Raid",
  "Paint Spill",
  "Goop",
  "Heat-Tint",
  "Welded",
  "Auzora",
  "Soul",
  "Gilded",
  "Candy",
  "Wiggle",
  "Choc",
  "VAX",
  "Kanagawa",
  "AKS",
  "AR Wired",
  "Cheetah",
  "Olympus Rifle",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Blaze AK",
  "Delirium",
  "Tropic Pop",
  "Arctic",
  "Fished",
  "Poseidon",
  "Tiger Rifle",
  "Zebra Rifle",
  "Aurora",
  "Impostor",
  "Stormy",
  "Ducky",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Sky Rifle",
  "Pirate",
  "Hemp",
  "Kunzite",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Toya",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Us",
  "Dipped Blackout",
  "Sticker bomb",
  "Cygento",
  "Clouded",
  "Wrapped up AK",
  "Volcanic",
  "Chartreuse",
  "Binary Tech",
  "Future Tech",
  "Tortobe",
  "AK Octo",
  "Raid",
  "Versate",
  "Purpur",
  "Vapormoon",
  "Tesselate",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Fabrica",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "RedTec",
  "Tangible Flavor",
  "SpaceBeeto",
  "B93re",
  "Binary Tech",
  "Future Tech",
  "Aristocrat",
  "Raid",
  "Volcanic",
  "Dipped Blackout",
  "Polymer",
  "Parabellum",
  "Poly Fade",
  "Retro-cade",
  "SMG Wired",
  "Candy",
  "Wiggle",
  "Choc",
  "Aquarium",
  "Krunkstruct",
  "Bloodmoon",
  "Green Waves",
  "Purple Waves",
  "Goddess",
  "SMG Barbed",
  "Kittle",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "SMG Lazarus",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Explora",
  "Cyclonic Charge",
  "Disco Kill",
  "Cranium",
  "SMG Blaze",
  "Tau",
  "Brainstorm",
  "Koi",
  "SMG Tigris",
  "Yingyang",
  "Serpentine",
  "SMG Safari",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Hemp",
  "Kunzite",
  "Natrix",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "UMP Atmos",
  "Zander",
  "Abyssal Storm",
  "Medic 87",
  "Mother's Den",
  "SMG Iris",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "SMG Venom",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "SMG Wingman",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "StarPoint",
  "Dipped Blackout",
  "Sprayer",
  "Retro Strike",
  "Sticker bomb",
  "Wrapped up SMG",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Mass Produced",
  "Raid",
  "UMP Cygentro",
  "Chartreuse",
  "UMP Tortobe",
  "UMP Octo",
  "UMP Versate",
  "SMG Purpur",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Fabrica",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Paint Spill",
  "Goop",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Line Breaker",
  "Sunset claw",
  "Barbed Python",
  "Cranium",
  "Basilisk",
  "Golden Future",
  "Zephyr",
  "Vince",
  "Cyberkitty",
  "Harcollicegen",
  "Obsessed",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "REV Olympus",
  "Kunzite",
  "Merlot",
  "Octopod",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Pocket Cannon",
  "Legionnaire",
  "Blaze Python",
  "Engulfed",
  "Tiger Python",
  "Zebra Python",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Sky Python",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Dipped Blackout",
  "waterrmeeeelon",
  "Blue Fiber",
  "Sticker bomb",
  "Clouded",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Cracked",
  "Pro Build",
  "Raid",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Paint Spill",
  "Slime Spill",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Fabrica",
  "RevBG",
  "Aurum",
  "Depth",
  "Pearlescent",
  "Coach Barb",
  "SG Olympus",
  "Twin Blaze",
  "SG Tigris",
  "Safaris",
  "Sky Pump",
  "Safran",
  "Purple Rain",
  "Cobra",
  "Spectrum",
  "Blunderbuss",
  "Cranium",
  "Track 73",
  "Silver Teal",
  "RY4-S",
  "Prehistoric",
  "Lotus",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Kunzite",
  "Ho-Ho",
  "Pink Drip",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Blue Drip",
  "Tech2",
  "Olive",
  "Sugar Coat",
  "Radar",
  "Spruce",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Dijon",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Shattered Glass",
  "Jade Tiger",
  "Digiarmor",
  "Deep",
  "Sticker bomb",
  "Clouded",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Wide",
  "Mosaik",
  "Raid",
  "Picasso",
  "Snowy",
  "Hazard",
  "Cerise",
  "Quarantine",
  "Kiason",
  "HotRod",
  "Candy",
  "Halogen",
  "Exponentiat",
  "Mech Rainbow",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Tiger Cascade",
  "Knightingale",
  "Cranium",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Olympus LMG",
  "Kunzite",
  "Ho-Ho",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Jeager",
  "Tiger LMG",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Blaze LMG",
  "Zebra LMG",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Royal Tiger",
  "Street Maniac",
  "Sky LMG",
  "Sticker bomb",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Raid",
  "Fabrica",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Paint Spill",
  "Slime Spill",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Choc",
  "Barbed Auto",
  "Olympus MMA",
  "Blaze Auto",
  "Tiger MMA",
  "Zebra MMA",
  "Sky AUTO",
  "MMA Cygneto",
  "M14 Chartreuse",
  "MMA Tortobe",
  "MMA Octo",
  "MMA Versate",
  "MMA Purpur",
  "Black Ice",
  "Candy Cane",
  "Mistletoe",
  "Festivity",
  "Cockatrice",
  "Sugar Coat",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Dipped Blackout",
  "Sticker bomb",
  "Clouded",
  "Volcanic",
  "Binary Tech",
  "Future Tech",
  "Voltaic",
  "Raid",
  "Metallic Swirl",
  "Tessilate",
  "Bubblegum",
  "Obsydian",
  "Carbonfibre",
  "Cobra",
  "Python",
  "Flamer",
  "Cranium",
  "Watercolours",
  "Sly",
  "Blood Diamond",
  "MKT",
  "Glorious",
  "Laminar",
  "Prey",
  "Sweety",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Hemp",
  "Kunzite",
  "Ghen",
  "Malignance",
  "Ho-Ho",
  "Radar",
  "Spooky Festival",
  "Shiplap",
  "Alienator",
  "Skullz N Bulletz",
  "Krystallizer",
  "Psycho Loop",
  "Flower Dance",
  "Prisma",
  "Secret Level",
  "Starfrost",
  "Book of Shadows",
  "Barbed Launcher",
  "Olympus Launcher",
  "Blaze RL",
  "Tiger Rocket",
  "Zebra Launcher",
  "Sky Launcher",
  "Fabrica",
  "Cracked",
  "Fire Stream",
  "Ripped Sun",
  "Bliss Flow",
  "Kenzo",
  "Paint Spill",
  "Goop",
  "Boneclaw",
  "Cascade",
  "War Torn",
  "Emoji",
  "Rich",
  "Rainbow Sky",
  "Pirate",
  "Kunzite",
  "Sugar Coat",
];

export const rare_labels = [
  "Green Headset",
  "Red Headset",
  "Beats",
  "Pink Ops",
  "Mustache",
  "Pot",
  "Crunch",
  "Vocal",
  "Casual",
  "Welder Mask",
  "Grey Hat",
  "Black Hat",
  "Brown Hat",
  "Green Capper",
  "Sports Capper",
  "Race Capper",
  "Street Capper",
  "Star Capper",
  "Kitkap",
  "Diver Goggles",
  "Pink Bow",
  "Yellow Bow",
  "Cool Cap",
  "Mad Cap",
  "Ace Cap",
  "Ice Cap",
  "Red Tinted Goggles",
  "Blue Tinted Goggles",
  "Ushanka",
  "Snorkle",
  "Goggles",
  "Brown Stache",
  "Black Stache",
  "Big Cheese",
  "Black Curly Stache",
  "Ginger Curly Stache",
  "Boxxy",
  "Executioner",
  "Ginger",
  "Black Hair",
  "Bee Antlers",
  "Blonde Stubbles",
  "Old Man Stubbles",
  "Red Bandana",
  "Krunkie Glasses",
  "Mr. Cacti",
  "Joystick",
  "Eye Patch",
  "Antenna",
  "Fangs",
  "Lilly Pad",
  "Goblin on these",
  "Bad News",
  "Booked",
  "Umbrella",
  "Neon KR",
  "Bunkered",
  "Sturm Helmet",
  "Outback Hat",
  "Dundee Hat",
  "Red Hat",
  "Urban Soldier",
  "Desert Soldier",
  "Arctic Soldier",
  "Pinata",
  "Sombrerro",
  "Submergence",
  "Mowhawk",
  "Wipers",
  "Gold Sunnies",
  "Munchie",
  "Arrowhead",
  "Egghead",
  "Blonde Beard",
  "Brown Beard",
  "Aged Beard",
  "TTV-Cap",
  "Chef",
  "Sunflower",
  "Lavender",
  "Django",
  "Cattleman",
  "Sailor",
  "Ushanka",
  "Private",
  "Purple Bandana",
  "Red Bandana",
  "Peanut",
  "Purple Button",
  "Green Button",
  "Red Backpack",
  "Blue Backpack",
  "Krinkers Bar",
  "Nepillow",
  "Police Vest",
  "KRC Bucket",
  "Quiver",
  "White Checkmate",
  "Black Checkmate",
  "Rewarded",
  "Torched",
  "Bell",
  "Hive",
  "Tourist",
  "Fireworker",
  "Copium",
  "Clocked",
  "Just N' Egg",
  "Flag",
  "Krunky Safe",
  "Yellow Scuba",
  "Blue Scuba",
  "Red Ski",
  "Green Ski",
  "Soldier Pack",
  "Red Backpack",
  "Blue Backpack",
  "Green Backpack",
  "Yellow Backpack",
  "Roller Backpack",
  "Baller Backpack",
  "Todo List",
  "Basket",
  "Krunkie",
  "Hydrate",
  "Arctic Hunt",
  "Autumn Hunt",
  "Arctic",
  "Exoscarlet",
  "Polly",
  "Zig-Zag",
  "Eco",
  "Musk",
  "Sugar Kiss",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "AWP Mech",
  "Morgana",
  "Scoped Tuscan",
  "Ignis",
  "Honeycomb",
  "Sweety",
  "Stormy",
  "Ducky",
  "Autumn",
  "Alpes",
  "Love",
  "Puzzler",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "AWP Iris",
  "Bolt Wanderer",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Vlaine",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Post-it",
  "New-Wave",
  "Aquarium",
  "Haunted",
  "Sunset",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Scharfschutze",
  "Blue Digital",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Pink Drip",
  "Blue Drip",
  "Hazard Reticle",
  "Red Splat",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Kodac Reticle",
  "Green Poly",
  "Blue Poly",
  "Picnic",
  "Dual Woodland",
  "Flecken Uzi",
  "Rapid Digital",
  "Torn Dual",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Aquarium",
  "Haunted",
  "Sunrise",
  "Dawn",
  "Geometrika",
  "Tiger Blood",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Ignis",
  "Autumn",
  "Alpes",
  "Love",
  "Puzzler",
  "Tsunami",
  "Merlot",
  "Huckleberry",
  "Sketch",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Arctic",
  "Autumn Burst",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Morgana",
  "Ignis",
  "Machinist",
  "Sweety",
  "Stormy",
  "Ducky",
  "Autumn",
  "Alpes",
  "Puzzler",
  "Tsunami",
  "Hemp",
  "Honey Badger",
  "Merlot",
  "Huckleberry",
  "Dotted",
  "Jingles",
  "G2 Moss",
  "Cookie",
  "Wrapper",
  "Gifted",
  "F1 Marshland",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Blue Digital",
  "Green Digital",
  "Post-It",
  "Retro-Noise",
  "Haunted",
  "Dawn",
  "Geometrika",
  "Purple Digital",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Pink Drip",
  "Blue Drip",
  "Bushwalker",
  "Red Splat",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Green Poly",
  "Blue Poly",
  "Burst Hazard",
  "Kodac Famas",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Retro-Noise",
  "Sunrise",
  "Dawn",
  "Geometrika",
  "Haunted",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Arctic AK",
  "Autumn AK",
  "Puma AR",
  "Zig-Zag",
  "Eco",
  "Musk",
  "Sugar Kiss",
  "Mach Rifle",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "AR Tuscan",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Mossy Rifle",
  "Morgana",
  "Autumn",
  "Alpes",
  "Love",
  "Puzzler",
  "Tsunami",
  "Merlot",
  "Huckleberry",
  "Sketch",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "AR Saphire",
  "AR Jade",
  "AR Plexus",
  "AR Lapis",
  "Hawker",
  "Master Of Potions",
  "Snake Pit",
  "AR Altis",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Liquid",
  "Mysterious Footprints",
  "Starpunk",
  "Clementine",
  "Laurel",
  "Crimson",
  "Azure",
  "Laguna",
  "Cygenta",
  "Retro-Noise",
  "Haunted",
  "Aquarium",
  "Sunset",
  "Dawn",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Flecken AK",
  "Blue Digital",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Hazard AK",
  "Pink Drip",
  "Blue Drip",
  "Red Splat",
  "Kodac AK",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Green Poly",
  "Blue Poly",
  "Glacies",
  "Fulgur",
  "Cellula",
  "Lineae",
  "SMG Arctic",
  "SMG Autumn",
  "SMG Puma",
  "Zig-Zag",
  "Eco",
  "Musk",
  "Sugar Kiss",
  "SMG Machinist",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "SMG Tuscan",
  "Lost",
  "Morgana",
  "SMG Growth",
  "Ignis",
  "Sweety",
  "Stormy",
  "Ducky",
  "Autumn",
  "Alpes",
  "Love",
  "Puzzler",
  "Tsunami",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "UMP Saphire",
  "Starpunk",
  "UMP Jade",
  "UMP Plexus",
  "Post-it",
  "New-Wave",
  "Retro-Noise",
  "Haunted",
  "Sunset",
  "Dawn",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "SMG Flecken",
  "Clementine",
  "SMG Auburn",
  "UMP Laurel",
  "UMP Crimson",
  "UMP Azure",
  "Laguna",
  "UMP Cygenta",
  "Blue Digital",
  "SMG Hazard",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Pink Drip",
  "SMG Kodac",
  "Blue Drip",
  "Red Splat",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Green Poly",
  "Blue Poly",
  "Arctic Python",
  "Autumn Python",
  "Puma Python",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Morgana",
  "Ignis",
  "Sweety",
  "Stormy",
  "Machinist Python",
  "Ducky",
  "Autumn",
  "Alpes",
  "Love",
  "Puzzler",
  "Pirate",
  "Tsunami",
  "Hemp",
  "Huckleberry",
  "Tuscan Revolver",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Mossy Python",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "New-Wave",
  "Retro-Noise",
  "Haunted",
  "Picnic",
  "Sunset",
  "Dawn",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Flecken Python",
  "Blue Digital",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Hazard Python",
  "Blue Poly",
  "Pink Drip",
  "Blue Drip",
  "Red Splat",
  "Purple Splat",
  "Kodac Python",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Green Poly",
  "Blue Poly",
  "Arctic Slug",
  "Autumn Slug",
  "Slug Puma",
  "MD Frag",
  "SG Tuscan",
  "Gabrand",
  "Flecken",
  "Hazard Slug",
  "Kodac Slug",
  "Morgana",
  "Ignis",
  "Pink Poly",
  "Orange Poly",
  "Sweety",
  "Stormy",
  "Ducky",
  "Green Poly",
  "Autumn",
  "Alpes",
  "Puzzler",
  "Tsunami",
  "Hemp",
  "Blue Poly",
  "Merlot",
  "Huckleberry",
  "Dotted",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Sepia",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Red Splat",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Comb",
  "Red Comb",
  "New-Wave",
  "Retro-Noise",
  "Green Comb",
  "Haunted",
  "Sunset",
  "Dawn",
  "Geometrika",
  "Blue Comb",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Sandstorm",
  "Picnic",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Zig-Zag",
  "Eco",
  "Musk",
  "Sugar Kiss",
  "Tiger Blood",
  "Scalamandre",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Arctic LMG",
  "Autumn LMG",
  "Tiger Maine",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Puma LMG",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Morgana",
  "Ignis",
  "Sweety",
  "Stormy",
  "Ducky",
  "Machinist LMG",
  "Autumn",
  "Alpes",
  "Puzzler",
  "Tsunami",
  "Hemp",
  "Merlot",
  "Huckleberry",
  "Dotted",
  "Jingles",
  "Tuscan LMG",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Mossy LMG",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Retro-Noise",
  "Haunted",
  "Sunset",
  "Dawn",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Lineae",
  "Glacies",
  "Green Poly",
  "Blue Poly",
  "Flecken LMG",
  "Blue Digital",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Hazard LMG",
  "Pink Drip",
  "Blue Drip",
  "Red Splat",
  "Purple Splat",
  "Orange Splat",
  "Kodac LMG",
  "Green Splat",
  "Yellow Poly",
  "Red Poly",
  "Zig-Zag",
  "Eco",
  "Musk",
  "Sugar Kiss",
  "Candy",
  "Tiger Blood",
  "Scalamandre",
  "Arctic Auto",
  "Autumn Auto",
  "Mach Auto",
  "Puma MMR",
  "Auto Machinist",
  "Tuscan MMA",
  "Overgrowth",
  "Saphire",
  "Jade",
  "Plexus",
  "Lapis",
  "MMA Liquid",
  "MMA Auburn",
  "MMA Laurel",
  "MMA Crimson",
  "Flecken Auto",
  "MMA Azure",
  "MMA Laguna",
  "MMA Cygneta",
  "Mach 3",
  "Bloodripper",
  "Hazard Auto",
  "Kodac Auto",
  "Jingles",
  "Cookie",
  "Wrapper",
  "Gifted",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Tiger Blood",
  "Retro-Noise",
  "Aquarium",
  "Scalamandre",
  "Dawn",
  "Geometrika",
  "Fulgur",
  "Cellula",
  "Tiger Maine",
  "Lineae",
  "Glacies",
  "Leopard",
  "Peppermint",
  "Spearmint",
  "Pink Panther",
  "Amber",
  "Multicam",
  "Aquaric",
  "Heather",
  "Lost",
  "Morgana",
  "Ignis",
  "Stormy",
  "Ducky",
  "Autumn",
  "Alpes",
  "Puzzler",
  "Pirate",
  "Tsunami",
  "Merlot",
  "Huckleberry",
  "Dotted",
  "Arctic RL",
  "Autumn RL",
  "Hawker",
  "Master Of Potions",
  "8-Bit",
  "Puma RTL",
  "Snake Pit",
  "Lab-08",
  "Amber",
  "Back to Skool",
  "Monarch's Maze",
  "Doodlemania",
  "Gift Wrap",
  "Mysterious Footprints",
  "Starpunk",
  "Machinist Launcher",
  "Tuscan Launcher",
  "Mossy Rocket",
  "Blue Poly",
  "Flecken RL",
  "Blue Digital",
  "Green Digital",
  "Purple Digital",
  "Red Digital",
  "Pink Poly",
  "Orange Poly",
  "Green Poly",
  "Blue Poly",
  "Pink Drip",
  "Hazard RL",
  "Blue Drip",
  "Red Splat",
  "Purple Splat",
  "Orange Splat",
  "Green Splat",
  "Yellow Poly",
  "Kodac RL",
  "Red Poly",
  "Green Poly",
  "Sweety",
  "Stormy",
  "Ducky",
  "Autumn",
  "Alpes",
  "Puzzler",
  "Tsunami",
  "Hemp",
  "Merlot",
  "Huckleberry",
];

export const uncommon_labels = [
  "Cowboy Hat",
  "Red Beanie",
  "Blue Beanie",
  "Purple Cap",
  "Red Mask",
  "Black Mask",
  "Broadcasted",
  "Corked",
  "Black Cowboy Hat",
  "Brown Cowboy Hat",
  "Blue Hat",
  "Sun Glasses",
  "Ray Bam",
  "Queens Guard",
  "Afro",
  "Brown Afro",
  "Hard Hat",
  "Purple Beanie",
  "Red Beanie",
  "Blue Pom-Pom",
  "Green Pom-Pom",
  "Love-Cap",
  "Lucky-Cap",
  "Farmer",
  "Helper",
  "Blue Headband",
  "Red Headband",
  "Season 6 Starter Ticket",
  "Season 7 Starter Ticket",
  "Tiny Bell",
  "Green Kite",
  "Pink Glazed",
  "Blue Glazed",
  "Krunk-Bull",
  "Supersports Soda",
  "Soitsu Soda",
  "Absolute Soda",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Trail Scout",
  "Reticle Faded",
  "Puma Sniper",
  "Scoped Carbon",
  "Lime",
  "Berry",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Blushed Sniper",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Scoped Moss",
  "Illusion",
  "Swamped Scope",
  "Merlot",
  "Huckleberry",
  "Sketch",
  "Digital Hunt",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Ripper",
  "Drywall",
  "Retro-Noise",
  "Machinery",
  "Morse",
  "Pingere",
  "Woodland Sniper",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Sandstorm",
  "Picasso",
  "Seafarer",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Sap Uzi",
  "Grape",
  "Canvas",
  "Frankenstein",
  "Libra",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Psychedelic",
  "Violette",
  "Marv",
  "Ripper",
  "Basel",
  "Drywall",
  "Machinery",
  "Morse",
  "Pingere",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Morgana",
  "Lime",
  "Honeycomb",
  "Sweety",
  "Berry",
  "Illusion",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Burst Fade",
  "Basel",
  "G2 Puma",
  "Clover",
  "Burst Carbo",
  "Blue Maze",
  "Yellow Maze",
  "F1 Blush",
  "Honeycomb",
  "Illusion",
  "Love",
  "Sketch",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Ripper",
  "Drywall",
  "Machinery",
  "Morse",
  "Pingere",
  "Digital Burst",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Woodland",
  "Sandstorm",
  "Picnic",
  "Picasso",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Seafarer G2",
  "Lime",
  "G2 Trail",
  "Berry",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Ripper",
  "Drywall",
  "Morse",
  "Pingere",
  "Machinery",
  "Trail AK",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Faded AK",
  "Carbon AK",
  "Blushed AK",
  "Lime",
  "Berry",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Swamped AK",
  "Honeycomb",
  "Sweety",
  "Illusion",
  "Bark AK",
  "Rifle Wanderer",
  "Digital AK",
  "Perplex",
  "Frankenstein",
  "Trople",
  "8-Bit",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Dropper",
  "Ripper",
  "Drywall",
  "Machinery",
  "Morse",
  "Pingere",
  "Leaf",
  "Flame",
  "Aqua",
  "Gravel",
  "Woodland AK",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Sandstorm",
  "Seafarer AK",
  "Picnic",
  "Picasso",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Machinery",
  "Morse",
  "Pingere",
  "SMG Fade",
  "Red Drip",
  "Green Drip",
  "SMG Carbon",
  "Lime",
  "SMG Blossom",
  "Berry",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "SMG Marsh",
  "Honeycomb",
  "Illusion",
  "Merlot",
  "Huckleberry",
  "Sketch",
  "Birch SMG",
  "SMG Wanderer",
  "Frankenstein",
  "SMG Digital",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "UMP Lapis",
  "Perplex",
  "Ripper",
  "Drywall",
  "UMP Torpe",
  "SMG Como",
  "Machinery",
  "Morse",
  "Pingere",
  "SMG Liquid",
  "Dropper",
  "SMG Woodland",
  "Leaf",
  "Flame",
  "Aqua",
  "Gravel",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "SMG Seafarer",
  "Sandstorm",
  "Picnic",
  "Picasso",
  "SMG Trail",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Faded Python",
  "Berry",
  "Indigo",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Carbon Python",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Blushed Revolver",
  "Honeycomb",
  "Illusion",
  "Sketch",
  "Swamped Revolver",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Bark Python",
  "Wanderer Python",
  "Digital Python",
  "Ripper",
  "Drywall",
  "Machinery",
  "Morse",
  "Picasso",
  "Pingere",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Woodland",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Sandstorm",
  "Seafarer",
  "Trail Python",
  "Lime",
  "SG Fade",
  "SG Carbon",
  "Blossom",
  "Tennessee",
  "Bark Slug",
  "Slug Wanderer",
  "SG Digital",
  "Woodland",
  "Buccaneer",
  "SG Trail",
  "Red Digital",
  "Yellow Maze",
  "Honeycomb",
  "Illusion",
  "Love",
  "Sketch",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Ripper",
  "Drywall",
  "Machinery",
  "Morse",
  "Pingere",
  "Nova Pump",
  "Lime",
  "Berry",
  "Indigo",
  "Blue Digital",
  "Citrus",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Green Digital",
  "Purple Digital",
  "Clover",
  "Blue Maze",
  "Faded LMG",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Carbon LMG",
  "Blushed LMG",
  "Honeycomb",
  "Illusion",
  "Love",
  "Sketch",
  "Swamped LMG",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Ripper",
  "Drywall",
  "Bark LMG",
  "Machinery",
  "Morse",
  "Pingere",
  "LMG Wanderer",
  "Sandstorm",
  "Digital LMG",
  "Picnic",
  "Picasso",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Woodland LMG",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Seafarer LMG",
  "Lime",
  "Berry",
  "Indigo",
  "Citrus",
  "Trail LMG",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Psychedelic",
  "Violette",
  "Marv",
  "Basel",
  "Faded MMR",
  "Carbon MMR",
  "Blushed MMA",
  "Marshland",
  "Bark AUTO",
  "MMA Wanderer",
  "Digital Auto",
  "Perplexum",
  "Torped",
  "Commo",
  "Dropper",
  "Nature",
  "Woodland Auto",
  "Flame",
  "Aqua",
  "Earth",
  "Seafarer Auto",
  "Trail Auto",
  "Tangerine",
  "Grape",
  "Canvas",
  "Libra",
  "Frankenstein",
  "Psychedelic",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Violette",
  "Marv",
  "Basel",
  "Ripper",
  "Drywall",
  "Machinery",
  "Morse",
  "Pingere",
  "Clover",
  "Blue Maze",
  "Yellow Maze",
  "Lime",
  "Berry",
  "Honeycomb",
  "Illusion",
  "Love",
  "Indigo",
  "Citrus",
  "Sketch",
  "Faded RTL",
  "Frankenstein",
  "Crimson Feathers",
  "PaperCut Monsters",
  "Spectre Fish",
  "Carbon RTL",
  "Blushed Launcher",
  "Swamped Launcher",
  "Bark Launcher",
  "Wanderer Rocket",
  "Sandstorm",
  "Digital RL",
  "Picnic",
  "Picasso",
  "Snowy",
  "Ducky",
  "Graphite",
  "Porcelain",
  "Danger",
  "Cerise",
  "Orange Drip",
  "Red Drip",
  "Green Drip",
  "Woodland RL",
  "Sepia",
  "Olive",
  "Spruce",
  "Dijon",
  "Illusion",
  "Seafarer RL",
  "Love",
  "Trail RL",
  "Sketch",
  "Honeycomb",
];
